<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Classical Synthetic Control – Comparative Causal Metrics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-structural-bayesian-ts.html" rel="next">
<link href="./04-basic-diff-in-diff.html" rel="prev">
<link href="./images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-f1aadacce99040138bbb613f9330654f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0da87e08732b0aad79cc276a1be62fe2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-c77ee8f8b07d41e0e364fbf0a2ddebb9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-0da87e08732b0aad79cc276a1be62fe2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="custom.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-classical-synthetic-control.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Classical Synthetic Control</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Comparative Causal Metrics</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/quarcs-lab/ccm" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Comparative-Causal-Metrics.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-interrupted-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Interrupted Time Series</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-rd-in-time.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regression Discontinuity in Time</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-basic-diff-in-diff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Basic Differences-in-Differences</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-classical-synthetic-control.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Classical Synthetic Control</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-structural-bayesian-ts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Structural Bayesian Time Series</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-scm-idea" id="toc-the-scm-idea" class="nav-link active" data-scroll-target="#the-scm-idea"><span class="header-section-number">5.1</span> The SCM idea</a></li>
  <li><a href="#the-four-stage-tidysynth-pipeline" id="toc-the-four-stage-tidysynth-pipeline" class="nav-link" data-scroll-target="#the-four-stage-tidysynth-pipeline"><span class="header-section-number">5.2</span> The four-stage tidysynth pipeline</a></li>
  <li><a href="#the-equation" id="toc-the-equation" class="nav-link" data-scroll-target="#the-equation"><span class="header-section-number">5.3</span> The equation</a></li>
  <li><a href="#setup-and-data" id="toc-setup-and-data" class="nav-link" data-scroll-target="#setup-and-data"><span class="header-section-number">5.4</span> Setup and data</a></li>
  <li><a href="#fit-the-synthetic-control-pipeline" id="toc-fit-the-synthetic-control-pipeline" class="nav-link" data-scroll-target="#fit-the-synthetic-control-pipeline"><span class="header-section-number">5.5</span> Fit the synthetic-control pipeline</a></li>
  <li><a href="#donor-weights-and-predictor-weights" id="toc-donor-weights-and-predictor-weights" class="nav-link" data-scroll-target="#donor-weights-and-predictor-weights"><span class="header-section-number">5.6</span> Donor weights and predictor weights</a>
  <ul class="collapse">
  <li><a href="#a-closer-look-at-the-v-matrix" id="toc-a-closer-look-at-the-v-matrix" class="nav-link" data-scroll-target="#a-closer-look-at-the-v-matrix"><span class="header-section-number">5.6.1</span> A closer look at the V matrix</a></li>
  </ul></li>
  <li><a href="#the-estimate" id="toc-the-estimate" class="nav-link" data-scroll-target="#the-estimate"><span class="header-section-number">5.7</span> The estimate</a></li>
  <li><a href="#predictor-balance-did-the-matching-work" id="toc-predictor-balance-did-the-matching-work" class="nav-link" data-scroll-target="#predictor-balance-did-the-matching-work"><span class="header-section-number">5.8</span> Predictor balance: did the matching work?</a></li>
  <li><a href="#visualising-the-post-period-gap" id="toc-visualising-the-post-period-gap" class="nav-link" data-scroll-target="#visualising-the-post-period-gap"><span class="header-section-number">5.9</span> Visualising the post-period gap</a></li>
  <li><a href="#inference-via-placebo-permutation" id="toc-inference-via-placebo-permutation" class="nav-link" data-scroll-target="#inference-via-placebo-permutation"><span class="header-section-number">5.10</span> Inference via placebo permutation</a></li>
  <li><a href="#mspe-ratio-and-fisher-exact-p-value" id="toc-mspe-ratio-and-fisher-exact-p-value" class="nav-link" data-scroll-target="#mspe-ratio-and-fisher-exact-p-value"><span class="header-section-number">5.11</span> MSPE ratio and Fisher exact p-value</a></li>
  <li><a href="#inspecting-the-nested-tidysynth-object" id="toc-inspecting-the-nested-tidysynth-object" class="nav-link" data-scroll-target="#inspecting-the-nested-tidysynth-object"><span class="header-section-number">5.12</span> Inspecting the nested tidysynth object</a></li>
  <li><a href="#recap" id="toc-recap" class="nav-link" data-scroll-target="#recap"><span class="header-section-number">5.13</span> Recap</a></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading"><span class="header-section-number">5.14</span> Further reading</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/quarcs-lab/ccm/edit/main/05-classical-synthetic-control.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/quarcs-lab/ccm/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Classical Synthetic Control</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="the-scm-idea" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="the-scm-idea"><span class="header-section-number">5.1</span> The SCM idea</h2>
<p>Synthetic Control stops using one control state. Instead, it builds a <em>weighted combination</em> of donor states that matches the treated unit’s pre-period as closely as possible on a chosen set of predictors. The weighted combination is “synthetic California”. The gap between observed California and synthetic California is the estimated effect.</p>
<p><strong>Why it works where DiD failed.</strong> Difference-in-Differences against Nevada (chapter 4) needed parallel pre-trends with <em>one</em> neighbour. Synthetic Control needs parallel pre-trends with a <em>data-driven blend</em> of many neighbours. The optimisation does the matching, so the analyst no longer has to pick “the right” control state by hand.</p>
</section>
<section id="the-four-stage-tidysynth-pipeline" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="the-four-stage-tidysynth-pipeline"><span class="header-section-number">5.2</span> The four-stage tidysynth pipeline</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A["1. synthetic_control()&lt;br/&gt;declare treated unit&lt;br/&gt;and intervention time"] --&gt; B["2. generate_predictor()&lt;br/&gt;define matching variables&lt;br/&gt;(one call per time window)"]
    B --&gt; C["3. generate_weights()&lt;br/&gt;optimise donor weights&lt;br/&gt;(quadratic programming)"]
    C --&gt; D["4. generate_control()&lt;br/&gt;build synthetic California&lt;br/&gt;and post-period gap series"]
    D --&gt; E["5. plot_/grab_ helpers&lt;br/&gt;trends, weights,&lt;br/&gt;placebos, MSPE ratio,&lt;br/&gt;Fisher exact p-value"]

    style A fill:#6a9bcc,stroke:#141413,color:#fff
    style B fill:#6a9bcc,stroke:#141413,color:#fff
    style C fill:#6a9bcc,stroke:#141413,color:#fff
    style D fill:#d97757,stroke:#141413,color:#fff
    style E fill:#00d4c8,stroke:#141413,color:#141413
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Stages 1–4 produce the estimate. Stage 5 is a battery of inspection helpers — <code>plot_trends()</code>, <code>plot_differences()</code>, <code>plot_weights()</code>, <code>plot_placebos()</code>, <code>plot_mspe_ratio()</code>, <code>grab_unit_weights()</code>, <code>grab_predictor_weights()</code>, <code>grab_balance_table()</code>, <code>grab_significance()</code> — that turn the fitted object into figures and tables. We use all of them below.</p>
</section>
<section id="the-equation" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="the-equation"><span class="header-section-number">5.3</span> The equation</h2>
<p>Let <span class="math inline">\(X_1\)</span> be the vector of <span class="math inline">\(k\)</span> pre-period predictors for the treated unit (California), and let <span class="math inline">\(X_0\)</span> be the <span class="math inline">\(k \times J\)</span> matrix holding the same predictors for the <span class="math inline">\(J = 38\)</span> donor states. The Synthetic Control estimator chooses donor weights <span class="math inline">\(w\)</span> to minimise the (V-weighted) discrepancy between treated and synthetic on the predictors:</p>
<p><span class="math display">\[w^* \, = \, \arg\min_{w \in \mathcal{W}} \, \big(X_1 - X_0 w\big)^\top V \big(X_1 - X_0 w\big),\]</span></p>
<p>subject to</p>
<p><span class="math display">\[\mathcal{W} = \big\{w \in \mathbb{R}^J \,:\, w_j \ge 0 \,\, \forall j, \,\, \textstyle\sum_{j=1}^J w_j = 1\big\}.\]</span></p>
<p>The diagonal matrix <span class="math inline">\(V\)</span> holds the <strong>predictor</strong> importance weights — the optimiser can care more about pre-period cigarette sales than about, say, beer consumption (we inspect <span class="math inline">\(V\)</span> below). Once <span class="math inline">\(w^*\)</span> is solved, the synthetic California outcome at any year <span class="math inline">\(t\)</span> is</p>
<p><span class="math display">\[\widehat{Y_{1t}(0)} = \sum_{j=1}^J w_j^* \, Y_{jt},\]</span></p>
<p>and the ATT over 1989–2000 is the mean post-period gap between observed California and that synthetic counterfactual.</p>
</section>
<section id="setup-and-data" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="setup-and-data"><span class="header-section-number">5.4</span> Setup and data</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidysynth)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>prop99 <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/proposition99.rds"</span>) <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="fit-the-synthetic-control-pipeline" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="fit-the-synthetic-control-pipeline"><span class="header-section-number">5.5</span> Fit the synthetic-control pipeline</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>prop99_syn <span class="ot">&lt;-</span> prop99 <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1. Declare the panel structure: outcome, unit, time, treated unit</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    ("California"), and the last full pre-period year (1988).</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    generate_placebos = TRUE also fits the model treating each donor</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    state as treated, for the permutation test below.</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">synthetic_control</span>(</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">outcome  =</span> cigsale, <span class="at">unit =</span> state, <span class="at">time =</span> year,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">i_unit   =</span> <span class="st">"California"</span>, <span class="at">i_time =</span> <span class="dv">1988</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">generate_placebos =</span> <span class="cn">TRUE</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2. Predictors averaged over the full pre-period (1980-1988).</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate_predictor</span>(</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">time_window =</span> <span class="dv">1980</span><span class="sc">:</span><span class="dv">1988</span>,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">lnincome    =</span> <span class="fu">mean</span>(lnincome, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">retprice    =</span> <span class="fu">mean</span>(retprice, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">age15to24   =</span> <span class="fu">mean</span>(age15to24, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2b. beer is sparser, so use a narrower window where data is densest.</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate_predictor</span>(<span class="at">time_window =</span> <span class="dv">1984</span><span class="sc">:</span><span class="dv">1988</span>,</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>                     <span class="at">beer =</span> <span class="fu">mean</span>(beer, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2c. Three "lagged outcomes" - cigsale at three pre-period dates.</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  <span class="co">#     These pin synthetic California's pre-period trajectory.</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate_predictor</span>(<span class="at">time_window =</span> <span class="dv">1975</span>, <span class="at">cigsale_1975 =</span> cigsale) <span class="sc">|&gt;</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate_predictor</span>(<span class="at">time_window =</span> <span class="dv">1980</span>, <span class="at">cigsale_1980 =</span> cigsale) <span class="sc">|&gt;</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate_predictor</span>(<span class="at">time_window =</span> <span class="dv">1988</span>, <span class="at">cigsale_1988 =</span> cigsale) <span class="sc">|&gt;</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3. Solve the constrained QP for donor weights w*. The three IPOP</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    parameters are tuning knobs for the interior-point optimiser.</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate_weights</span>(<span class="at">optimization_window =</span> <span class="dv">1970</span><span class="sc">:</span><span class="dv">1988</span>,</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>                   <span class="at">margin_ipop =</span> .<span class="dv">02</span>,</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>                   <span class="at">sigf_ipop   =</span> <span class="dv">7</span>,</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>                   <span class="at">bound_ipop  =</span> <span class="dv">6</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 4. Compute the synthetic California series from w* and donor outcomes.</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate_control</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>Predictor choices.</strong> Seven predictors are passed in. Three are pre-period covariate averages over the full pre-period (<code>lnincome</code>, <code>retprice</code>, <code>age15to24</code> over 1980–1988). One uses a narrower window where data is densest (<code>beer</code> over 1984–1988). Three are <em>lagged outcomes</em> — cigarette sales themselves at 1975, 1980, and 1988. The lagged outcomes are the most important trick: anchoring the synthetic control on the treated unit’s own pre-period <em>outcome levels</em> at multiple time points forces the synthetic series to track California’s pre-1988 trajectory closely.</p>
</section>
<section id="donor-weights-and-predictor-weights" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="donor-weights-and-predictor-weights"><span class="header-section-number">5.6</span> Donor weights and predictor weights</h2>
<p>The optimisation produces two weight vectors that drive the entire fit. Both are extractable as tidy tables.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grab_unit_weights</span>(prop99_syn) <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(weight)) <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 2
  unit            weight
  &lt;chr&gt;            &lt;dbl&gt;
1 Utah        0.342     
2 Nevada      0.238     
3 Montana     0.209     
4 Colorado    0.149     
5 Connecticut 0.0617    
6 New Mexico  0.000434  
7 Idaho       0.00000341
8 Wisconsin   0.00000254</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grab_predictor_weights</span>(prop99_syn) <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(weight))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  variable       weight
  &lt;chr&gt;           &lt;dbl&gt;
1 cigsale_1975 0.468   
2 cigsale_1980 0.412   
3 retprice     0.0546  
4 cigsale_1988 0.0366  
5 beer         0.0204  
6 age15to24    0.00733 
7 lnincome     0.000291</code></pre>
</div>
</div>
<p>Two things to notice.</p>
<ol type="1">
<li><strong>Five states absorb essentially 100% of the donor weight.</strong> Utah, Nevada, Montana, Colorado, Connecticut. Every other state gets effectively zero. California is matched mostly to other Western/sunbelt states with similar age structure and cigarette price levels, plus Connecticut as a smoking-rate counterweight from the east.</li>
<li><strong>The two earliest cigsale levels dominate the V matrix.</strong> <code>cigsale_1975</code> and <code>cigsale_1980</code> together get roughly 88% of the predictor weight. The four behavioural and demographic covariates get less than 9% combined. The optimiser has effectively decided: “the best way to predict California’s cigarette sales is using <em>other states’ cigarette sales</em>.”</li>
</ol>
<p>For a one-line visual of both weight vectors, tidysynth ships a <code>plot_weights()</code> helper:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_weights</span>(prop99_syn)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-sc-weights" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sc-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-classical-synthetic-control_files/figure-html/fig-sc-weights-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sc-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Donor unit weights (left) and predictor V-matrix weights (right) from tidysynth.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="a-closer-look-at-the-v-matrix" class="level3" data-number="5.6.1">
<h3 data-number="5.6.1" class="anchored" data-anchor-id="a-closer-look-at-the-v-matrix"><span class="header-section-number">5.6.1</span> A closer look at the V matrix</h3>
<p>The combined <code>plot_weights()</code> view is convenient, but the V matrix deserves a stand-alone chart because it answers a different question than the donor weights. Donor weights say <em>which states</em> mimic California; the V matrix says <em>which variables</em> the optimiser used to decide what “mimics” means.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>predw_df <span class="ot">&lt;-</span> <span class="fu">grab_predictor_weights</span>(prop99_syn) <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="fu">fct_reorder</span>(variable, weight))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(predw_df, <span class="fu">aes</span>(<span class="at">x =</span> weight, <span class="at">y =</span> variable)) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"#6a9bcc"</span>) <span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, weight)), <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.12</span>) <span class="sc">+</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))) <span class="sc">+</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"V-matrix weight (predictor importance)"</span>, <span class="at">y =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-sc-predictor-weights" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sc-predictor-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-classical-synthetic-control_files/figure-html/fig-sc-predictor-weights-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sc-predictor-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: V matrix: cigsale_1975 and cigsale_1980 dominate; behavioural covariates get nearly zero weight.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Two readings of the same picture, one practical and one cautionary.</p>
<ul>
<li><em>Practical reading.</em> Two lagged outcomes (<code>cigsale_1975</code> and <code>cigsale_1980</code>) carry the bulk of the matching information. The optimiser has decided that California’s pre-period cigarette sales — <em>at multiple time points</em> — are the best fingerprint to match.</li>
<li><em>Cautionary reading.</em> The V matrix is <strong>not a causal ranking</strong>. It tells you which variables were <em>useful for matching the treated unit’s pre-period</em>, not which variables <em>cause</em> the outcome.</li>
</ul>
<p><strong>Common pitfall.</strong> Treating the V matrix as a list of causal drivers. It is a list of <em>good pre-period predictors for one specific unit</em>, not a structural model of smoking.</p>
</section>
</section>
<section id="the-estimate" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="the-estimate"><span class="header-section-number">5.7</span> The estimate</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># grab_synthetic_control() returns a tidy tibble with observed (real_y)</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and synthetic (synth_y) cigsale for every year. We restrict to the</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># post-period and compute the per-year gap.</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>sc_post <span class="ot">&lt;-</span> <span class="fu">grab_synthetic_control</span>(prop99_syn) <span class="sc">|&gt;</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(time_unit <span class="sc">&gt;</span> <span class="dv">1988</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dif =</span> real_y <span class="sc">-</span> synth_y)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Average the per-year gap to recover the ATT.</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(sc_post<span class="sc">$</span>dif)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -18.84561</code></pre>
</div>
</div>
<p>The Synthetic Control ATT is approximately <strong><span class="math inline">\(-18.85\)</span> packs/capita</strong> averaged over 1989–2000. This is the book’s primary causal estimate and within rounding of the canonical <span class="citation" data-cites="abadie2010synthetic">Abadie et al. (<a href="references.html#ref-abadie2010synthetic" role="doc-biblioref">2010</a>)</span> result.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_trends</span>(prop99_syn)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.
ℹ The deprecated feature was likely used in the tidysynth package.
  Please report the issue to the authors.</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-sc-trends" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sc-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-classical-synthetic-control_files/figure-html/fig-sc-trends-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sc-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.3: Synthetic Control: California (observed) vs synthetic California (weighted donor combination).
</figcaption>
</figure>
</div>
</div>
</div>
<p>The pre-period fit is excellent — the synthetic and observed series are nearly indistinguishable through 1988. A substantial gap opens immediately after 1989, widening to roughly 30 packs by 2000.</p>
</section>
<section id="predictor-balance-did-the-matching-work" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="predictor-balance-did-the-matching-work"><span class="header-section-number">5.8</span> Predictor balance: did the matching work?</h2>
<p><code>grab_balance_table()</code> shows California, synthetic California, and the unweighted donor average side-by-side on every predictor.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grab_balance_table</span>(prop99_syn)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 4
  variable     California synthetic_California donor_sample
  &lt;chr&gt;             &lt;dbl&gt;                &lt;dbl&gt;        &lt;dbl&gt;
1 age15to24         0.174                0.174        0.173
2 lnincome         10.1                  9.85         9.83 
3 retprice         89.4                 89.4         87.3  
4 beer             24.3                 24.2         23.7  
5 cigsale_1975    127.                 127.         137.   
6 cigsale_1980    120.                 120.         138.   
7 cigsale_1988     90.1                 91.4        114.   </code></pre>
</div>
</div>
<p>On every variable, <em>synthetic California</em> is far closer to California than the unweighted donor average is. The most dramatic improvement is on the lagged outcomes: <code>cigsale_1988</code> is roughly 90 for California vs ≈91 for the synthetic — a near-perfect match — while the unweighted donor average is around 114. That gap of ~24 packs is exactly the bias the naive pre-post method silently absorbed.</p>
</section>
<section id="visualising-the-post-period-gap" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="visualising-the-post-period-gap"><span class="header-section-number">5.9</span> Visualising the post-period gap</h2>
<p><code>plot_trends()</code> showed <em>both</em> observed and synthetic California on one canvas. The companion helper <code>plot_differences()</code> plots just the <em>gap</em>: <span class="math inline">\(Y_{1t} - \widehat{Y_{1t}(0)}\)</span>, year by year. This isolates the treatment-effect curve in its cleanest form.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_differences</span>(prop99_syn)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• colour : ""
• linetype : ""</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-sc-differences" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sc-differences-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-classical-synthetic-control_files/figure-html/fig-sc-differences-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sc-differences-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.4: Per-year gap between observed California and synthetic California.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Read the line as the <em>effect of Proposition 99 on California in year <span class="math inline">\(t\)</span></em>. The pre-period values hover near zero (the matching worked), the line drops sharply after 1989, and it stays negative — steadily widening — throughout the post-period. The 1989–2000 mean of this series is exactly the <span class="math inline">\(-18.85\)</span> packs ATT reported above.</p>
</section>
<section id="inference-via-placebo-permutation" class="level2" data-number="5.10">
<h2 data-number="5.10" class="anchored" data-anchor-id="inference-via-placebo-permutation"><span class="header-section-number">5.10</span> Inference via placebo permutation</h2>
<p>A “standard error” computed as cross-year SD divided by <span class="math inline">\(\sqrt{N}\)</span> is <em>not</em> a real sampling-distribution-based standard error. The proper Synthetic Control uncertainty quantification is a permutation test.</p>
<p><strong>The recipe.</strong> Refit the synthetic-control model treating <em>each donor state</em> as if <em>it</em> had been the treated unit. Compute the post-period gap for each placebo. Compare California’s gap trajectory to those placebo trajectories. If California’s gap is extreme relative to the placebos, the policy probably did something.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_placebos</span>(prop99_syn)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-sc-placebos" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sc-placebos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-classical-synthetic-control_files/figure-html/fig-sc-placebos-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sc-placebos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.5: Placebo permutation: California in orange, donor placebos in grey (badly pre-fit donors pruned by default).
</figcaption>
</figure>
</div>
</div>
</div>
<p>The orange line is California; the grey lines are the donor placebos. By default, <code>plot_placebos()</code> <em>prunes</em> placebos whose pre-period mean squared prediction error (MSPE) exceeds twice California’s — those donors fit their own pre-period so badly that comparing their post-period gap to California’s would be misleading. After pruning, California’s post-period gap sits visibly below every retained placebo, which is the visual signature of a “real” treatment effect.</p>
<p>The unpruned variant keeps every donor for full transparency:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_placebos</span>(prop99_syn, <span class="at">prune =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-sc-placebos-unpruned" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sc-placebos-unpruned-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-classical-synthetic-control_files/figure-html/fig-sc-placebos-unpruned-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sc-placebos-unpruned-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.6: Same placebo plot with every donor retained — including badly pre-fit ones — to show the full pool of placebo trajectories.
</figcaption>
</figure>
</div>
</div>
</div>
<p>With pruning off, the grey cloud is messier and a few badly-fit donors swing wildly — but California’s post-period descent still ends up at the bottom of the bundle. The qualitative conclusion does not depend on the pruning rule.</p>
</section>
<section id="mspe-ratio-and-fisher-exact-p-value" class="level2" data-number="5.11">
<h2 data-number="5.11" class="anchored" data-anchor-id="mspe-ratio-and-fisher-exact-p-value"><span class="header-section-number">5.11</span> MSPE ratio and Fisher exact p-value</h2>
<p>A sharper version of the same test is the <strong>MSPE ratio</strong> — the ratio of post-period to pre-period mean squared prediction error. If a unit has a tight pre-period fit <em>and</em> a large post-period gap, the ratio is large.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># grab_significance() returns one row per unit (treated + every placebo)</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># with pre_mspe, post_mspe, the post/pre ratio, the unit's rank in that</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ratio, and the Fisher-style p-value (rank / n_units).</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">grab_significance</span>(prop99_syn) <span class="sc">|&gt;</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mspe_ratio)) <span class="sc">|&gt;</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 8
  unit_name     type    pre_mspe post_mspe mspe_ratio  rank fishers_exact_pvalue
  &lt;fct&gt;         &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;                &lt;dbl&gt;
1 California    Treated     3.17      392.      124.      1               0.0256
2 Georgia       Donor       3.79      179.       47.2     2               0.0513
3 Indiana       Donor      25.2       770.       30.6     3               0.0769
4 West Virginia Donor       9.52      284.       29.8     4               0.103 
5 Wisconsin     Donor      11.1       268.       24.1     5               0.128 
# ℹ 1 more variable: z_score &lt;dbl&gt;</code></pre>
</div>
</div>
<p>California’s MSPE ratio is around <strong>124</strong> — more than two and a half times higher than the next-highest unit. California ranks <strong>1st out of 39 units</strong>. The Fisher exact <span class="math inline">\(p\)</span>-value is rank divided by total units, so <span class="math inline">\(1/39 \approx 0.026\)</span>. Under the null hypothesis that Proposition 99 had no effect, the probability of seeing a unit this extreme purely by chance is about 2.6%.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_mspe_ratio</span>(prop99_syn)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• colour : ""</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-sc-mspe-ratio" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sc-mspe-ratio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-classical-synthetic-control_files/figure-html/fig-sc-mspe-ratio-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sc-mspe-ratio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.7: MSPE-ratio bar chart with California highlighted at rank 1 out of 39 units.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The orange bar at the top is California; every blue bar below it is a placebo donor. The gap between California and the second-place state is enormous. That gap is the visual signature of “a real treatment effect that the donor pool does not naturally replicate”.</p>
</section>
<section id="inspecting-the-nested-tidysynth-object" class="level2" data-number="5.12">
<h2 data-number="5.12" class="anchored" data-anchor-id="inspecting-the-nested-tidysynth-object"><span class="header-section-number">5.12</span> Inspecting the nested tidysynth object</h2>
<p><code>prop99_syn</code> is not a plain data frame — it is a <em>nested tibble</em> with one row per unit (treated unit + every donor refit as a placebo) and list-columns that hold every intermediate output of the optimisation.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>prop99_syn</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 78 × 11
   .id      .placebo .type .outcome .predictors .synthetic_control .unit_weights
   &lt;fct&gt;       &lt;dbl&gt; &lt;chr&gt; &lt;list&gt;   &lt;list&gt;      &lt;list&gt;             &lt;list&gt;       
 1 Califor…        0 trea… &lt;tibble&gt; &lt;tibble&gt;    &lt;tibble [31 × 3]&gt;  &lt;tibble&gt;     
 2 Califor…        0 cont… &lt;tibble&gt; &lt;tibble&gt;    &lt;tibble [31 × 3]&gt;  &lt;tibble&gt;     
 3 Alabama         1 trea… &lt;tibble&gt; &lt;tibble&gt;    &lt;tibble [31 × 3]&gt;  &lt;tibble&gt;     
 4 Alabama         1 cont… &lt;tibble&gt; &lt;tibble&gt;    &lt;tibble [31 × 3]&gt;  &lt;tibble&gt;     
 5 Arkansas        1 trea… &lt;tibble&gt; &lt;tibble&gt;    &lt;tibble [31 × 3]&gt;  &lt;tibble&gt;     
 6 Arkansas        1 cont… &lt;tibble&gt; &lt;tibble&gt;    &lt;tibble [31 × 3]&gt;  &lt;tibble&gt;     
 7 Colorado        1 trea… &lt;tibble&gt; &lt;tibble&gt;    &lt;tibble [31 × 3]&gt;  &lt;tibble&gt;     
 8 Colorado        1 cont… &lt;tibble&gt; &lt;tibble&gt;    &lt;tibble [31 × 3]&gt;  &lt;tibble&gt;     
 9 Connect…        1 trea… &lt;tibble&gt; &lt;tibble&gt;    &lt;tibble [31 × 3]&gt;  &lt;tibble&gt;     
10 Connect…        1 cont… &lt;tibble&gt; &lt;tibble&gt;    &lt;tibble [31 × 3]&gt;  &lt;tibble&gt;     
# ℹ 68 more rows
# ℹ 4 more variables: .predictor_weights &lt;list&gt;, .original_data &lt;list&gt;,
#   .meta &lt;list&gt;, .loss &lt;list&gt;</code></pre>
</div>
</div>
<p>Each list-column can be flattened with <code>tidyr::unnest()</code> for custom downstream work, or pulled out with one of the <code>grab_*()</code> helpers used above.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Flatten .outcome into a wide table: one row per (unit, year).</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The actual cigarette-sales column is named after each unit, so we</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># select metadata + California's series for a clean preview.</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>prop99_syn <span class="sc">|&gt;</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest</span>(<span class="at">cols =</span> <span class="fu">c</span>(.outcome)) <span class="sc">|&gt;</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(.id, .placebo, .type, time_unit, California) <span class="sc">|&gt;</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
  .id        .placebo .type   time_unit California
  &lt;fct&gt;         &lt;dbl&gt; &lt;chr&gt;       &lt;int&gt;      &lt;dbl&gt;
1 California        0 treated      1970       123 
2 California        0 treated      1971       121 
3 California        0 treated      1972       124.
4 California        0 treated      1973       124.
5 California        0 treated      1974       127.
6 California        0 treated      1975       127.
7 California        0 treated      1976       128 
8 California        0 treated      1977       126.</code></pre>
</div>
</div>
<p>For the tidy <em>observed-vs-synthetic</em> table (which is what most analyses want), the dedicated helper is more convenient:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grab_synthetic_control</span>(prop99_syn) <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
  time_unit real_y synth_y
      &lt;int&gt;  &lt;dbl&gt;   &lt;dbl&gt;
1      1970   123     117.
2      1971   121     119.
3      1972   124.    124.
4      1973   124.    125.
5      1974   127.    127.
6      1975   127.    127.
7      1976   128     128.
8      1977   126.    126.</code></pre>
</div>
</div>
<p>This is the whole point of the nested-tibble design: every step of the optimisation is <em>introspectable from R</em>, with no need to dig into S4 slots or <code>attr()</code> blobs.</p>
</section>
<section id="recap" class="level2" data-number="5.13">
<h2 data-number="5.13" class="anchored" data-anchor-id="recap"><span class="header-section-number">5.13</span> Recap</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Question</th>
<th>Answer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>What does Synthetic Control estimate?</td>
<td>The ATT on California, 1989–2000</td>
</tr>
<tr class="even">
<td>What is the point estimate?</td>
<td><strong><span class="math inline">\(-18.85\)</span> packs/capita per year</strong></td>
</tr>
<tr class="odd">
<td>What is “synthetic California”?</td>
<td>A convex combination of five Western/sunbelt states (Utah, Nevada, Montana, Colorado, Connecticut)</td>
</tr>
<tr class="even">
<td>What predictors did the matching?</td>
<td>Mostly two lagged outcomes — <code>cigsale_1975</code> and <code>cigsale_1980</code></td>
</tr>
<tr class="odd">
<td>How is the matching quality?</td>
<td>Excellent — synthetic and observed California are near-identical through 1988</td>
</tr>
<tr class="even">
<td>What is the inference statistic?</td>
<td>Fisher exact <span class="math inline">\(p \approx 0.026\)</span> (California ranks 1st out of 39 on the MSPE ratio)</td>
</tr>
<tr class="odd">
<td>What is the design-time pitfall?</td>
<td>Don’t read the V matrix as a list of causal drivers — it is a list of <em>good pre-period predictors</em></td>
</tr>
</tbody>
</table>
<p>Synthetic Control is the book’s headline causal estimate, and the placebo / MSPE-ratio diagnostics both confirm that California’s post-1989 trajectory is unusual relative to what other states experienced in the same window. In chapter 6 we hand the same donor information to a Bayesian model and ask whether a <em>credible interval</em> (a direct probability statement about the effect) tells the same story.</p>
</section>
<section id="further-reading" class="level2" data-number="5.14">
<h2 data-number="5.14" class="anchored" data-anchor-id="further-reading"><span class="header-section-number">5.14</span> Further reading</h2>
<ul>
<li><span class="citation" data-cites="abadie2010synthetic">Abadie et al. (<a href="references.html#ref-abadie2010synthetic" role="doc-biblioref">2010</a>)</span> — the original synthetic-control treatment of Proposition 99.</li>
<li><span class="citation" data-cites="abadie2021using">Abadie (<a href="references.html#ref-abadie2021using" role="doc-biblioref">2021</a>)</span> — methodological feasibility, data requirements, and assumptions in a JEL review.</li>
<li><span class="citation" data-cites="dunford2024tidysynth">Dunford (<a href="references.html#ref-dunford2024tidysynth" role="doc-biblioref">2024</a>)</span> — documentation for the <code>tidysynth</code> package used here.</li>
</ul>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-abadie2021using" class="csl-entry" role="listitem">
Abadie, A. (2021). Using synthetic controls: Feasibility, data requirements, and methodological aspects. <em>Journal of Economic Literature</em>, <em>59</em>(2), 391–425. <a href="https://www.aeaweb.org/articles?id=10.1257/jel.20191450">https://www.aeaweb.org/articles?id=10.1257/jel.20191450</a>
</div>
<div id="ref-abadie2010synthetic" class="csl-entry" role="listitem">
Abadie, A., Diamond, A., &amp; Hainmueller, J. (2010). Synthetic control methods for comparative case studies: Estimating the effect of <span>California</span>’s tobacco control program. <em>Journal of the American Statistical Association</em>, <em>105</em>(490), 493–505. <a href="https://www.aeaweb.org/articles?id=10.1257/jasa.2010.ap08746">https://www.aeaweb.org/articles?id=10.1257/jasa.2010.ap08746</a>
</div>
<div id="ref-dunford2024tidysynth" class="csl-entry" role="listitem">
Dunford, E. (2024). <em>Tidysynth — a tidy implementation of the synthetic control method in <span>R</span></em>. GitHub repository. <a href="https://github.com/edunford/tidysynth">https://github.com/edunford/tidysynth</a>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04-basic-diff-in-diff.html" class="pagination-link" aria-label="Basic Differences-in-Differences">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Basic Differences-in-Differences</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-structural-bayesian-ts.html" class="pagination-link" aria-label="Structural Bayesian Time Series">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Structural Bayesian Time Series</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Classical Synthetic Control"</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">## The SCM idea</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>Synthetic Control stops using one control state. Instead, it builds a *weighted combination* of donor states that matches the treated unit's pre-period as closely as possible on a chosen set of predictors. The weighted combination is "synthetic California". The gap between observed California and synthetic California is the estimated effect.</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>**Why it works where DiD failed.** Difference-in-Differences against Nevada (chapter 4) needed parallel pre-trends with *one* neighbour. Synthetic Control needs parallel pre-trends with a *data-driven blend* of many neighbours. The optimisation does the matching, so the analyst no longer has to pick "the right" control state by hand.</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="fu">## The four-stage tidysynth pipeline</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="in">```{mermaid}</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>flowchart LR</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>    A[<span class="ot">"</span><span class="st">1. synthetic_control()&lt;br/&gt;declare treated unit&lt;br/&gt;and intervention time</span><span class="ot">"</span>] --&gt; B[<span class="ot">"</span><span class="st">2. generate_predictor()&lt;br/&gt;define matching variables&lt;br/&gt;(one call per time window)</span><span class="ot">"</span>]</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>    B --&gt; C[<span class="ot">"</span><span class="st">3. generate_weights()&lt;br/&gt;optimise donor weights&lt;br/&gt;(quadratic programming)</span><span class="ot">"</span>]</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>    C --&gt; D[<span class="ot">"</span><span class="st">4. generate_control()&lt;br/&gt;build synthetic California&lt;br/&gt;and post-period gap series</span><span class="ot">"</span>]</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>    D --&gt; E[<span class="ot">"</span><span class="st">5. plot_/grab_ helpers&lt;br/&gt;trends, weights,&lt;br/&gt;placebos, MSPE ratio,&lt;br/&gt;Fisher exact p-value</span><span class="ot">"</span>]</span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>    style A fill:<span class="co">#6a9bcc,stroke:#141413,color:#fff</span></span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>    style B fill:<span class="co">#6a9bcc,stroke:#141413,color:#fff</span></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>    style C fill:<span class="co">#6a9bcc,stroke:#141413,color:#fff</span></span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>    style D fill:<span class="co">#d97757,stroke:#141413,color:#fff</span></span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>    style E fill:<span class="co">#00d4c8,stroke:#141413,color:#141413</span></span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>Stages 1–4 produce the estimate. Stage 5 is a battery of inspection helpers — <span class="in">`plot_trends()`</span>, <span class="in">`plot_differences()`</span>, <span class="in">`plot_weights()`</span>, <span class="in">`plot_placebos()`</span>, <span class="in">`plot_mspe_ratio()`</span>, <span class="in">`grab_unit_weights()`</span>, <span class="in">`grab_predictor_weights()`</span>, <span class="in">`grab_balance_table()`</span>, <span class="in">`grab_significance()`</span> — that turn the fitted object into figures and tables. We use all of them below.</span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a><span class="fu">## The equation</span></span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a>Let $X_1$ be the vector of $k$ pre-period predictors for the treated unit (California), and let $X_0$ be the $k \times J$ matrix holding the same predictors for the $J = 38$ donor states. The Synthetic Control estimator chooses donor weights $w$ to minimise the (V-weighted) discrepancy between treated and synthetic on the predictors:</span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a>$$w^* \, = \, \arg\min_{w \in \mathcal{W}} \, \big(X_1 - X_0 w\big)^\top V \big(X_1 - X_0 w\big),$$</span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a>subject to</span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-39"><a href="#cb30-39" aria-hidden="true" tabindex="-1"></a>$$\mathcal{W} = \big<span class="sc">\{</span>w \in \mathbb{R}^J \,:\, w_j \ge 0 \,\, \forall j, \,\, \textstyle\sum_{j=1}^J w_j = 1\big<span class="sc">\}</span>.$$</span>
<span id="cb30-40"><a href="#cb30-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-41"><a href="#cb30-41" aria-hidden="true" tabindex="-1"></a>The diagonal matrix $V$ holds the **predictor** importance weights — the optimiser can care more about pre-period cigarette sales than about, say, beer consumption (we inspect $V$ below). Once $w^*$ is solved, the synthetic California outcome at any year $t$ is</span>
<span id="cb30-42"><a href="#cb30-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-43"><a href="#cb30-43" aria-hidden="true" tabindex="-1"></a>$$\widehat{Y_{1t}(0)} = \sum_{j=1}^J w_j^* \, Y_{jt},$$</span>
<span id="cb30-44"><a href="#cb30-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-45"><a href="#cb30-45" aria-hidden="true" tabindex="-1"></a>and the ATT over 1989–2000 is the mean post-period gap between observed California and that synthetic counterfactual.</span>
<span id="cb30-46"><a href="#cb30-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-47"><a href="#cb30-47" aria-hidden="true" tabindex="-1"></a><span class="fu">## Setup and data</span></span>
<span id="cb30-48"><a href="#cb30-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-51"><a href="#cb30-51" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-52"><a href="#cb30-52" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb30-53"><a href="#cb30-53" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb30-54"><a href="#cb30-54" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb30-55"><a href="#cb30-55" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb30-56"><a href="#cb30-56" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidysynth)</span>
<span id="cb30-57"><a href="#cb30-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-58"><a href="#cb30-58" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb30-59"><a href="#cb30-59" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-60"><a href="#cb30-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-63"><a href="#cb30-63" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-64"><a href="#cb30-64" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: data-load</span></span>
<span id="cb30-65"><a href="#cb30-65" aria-hidden="true" tabindex="-1"></a>prop99 <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/proposition99.rds"</span>) <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>()</span>
<span id="cb30-66"><a href="#cb30-66" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-67"><a href="#cb30-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-68"><a href="#cb30-68" aria-hidden="true" tabindex="-1"></a><span class="fu">## Fit the synthetic-control pipeline</span></span>
<span id="cb30-69"><a href="#cb30-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-72"><a href="#cb30-72" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-73"><a href="#cb30-73" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fit-syn</span></span>
<span id="cb30-74"><a href="#cb30-74" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb30-75"><a href="#cb30-75" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb30-76"><a href="#cb30-76" aria-hidden="true" tabindex="-1"></a>prop99_syn <span class="ot">&lt;-</span> prop99 <span class="sc">|&gt;</span></span>
<span id="cb30-77"><a href="#cb30-77" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1. Declare the panel structure: outcome, unit, time, treated unit</span></span>
<span id="cb30-78"><a href="#cb30-78" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    ("California"), and the last full pre-period year (1988).</span></span>
<span id="cb30-79"><a href="#cb30-79" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    generate_placebos = TRUE also fits the model treating each donor</span></span>
<span id="cb30-80"><a href="#cb30-80" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    state as treated, for the permutation test below.</span></span>
<span id="cb30-81"><a href="#cb30-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">synthetic_control</span>(</span>
<span id="cb30-82"><a href="#cb30-82" aria-hidden="true" tabindex="-1"></a>    <span class="at">outcome  =</span> cigsale, <span class="at">unit =</span> state, <span class="at">time =</span> year,</span>
<span id="cb30-83"><a href="#cb30-83" aria-hidden="true" tabindex="-1"></a>    <span class="at">i_unit   =</span> <span class="st">"California"</span>, <span class="at">i_time =</span> <span class="dv">1988</span>,</span>
<span id="cb30-84"><a href="#cb30-84" aria-hidden="true" tabindex="-1"></a>    <span class="at">generate_placebos =</span> <span class="cn">TRUE</span></span>
<span id="cb30-85"><a href="#cb30-85" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb30-86"><a href="#cb30-86" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2. Predictors averaged over the full pre-period (1980-1988).</span></span>
<span id="cb30-87"><a href="#cb30-87" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate_predictor</span>(</span>
<span id="cb30-88"><a href="#cb30-88" aria-hidden="true" tabindex="-1"></a>    <span class="at">time_window =</span> <span class="dv">1980</span><span class="sc">:</span><span class="dv">1988</span>,</span>
<span id="cb30-89"><a href="#cb30-89" aria-hidden="true" tabindex="-1"></a>    <span class="at">lnincome    =</span> <span class="fu">mean</span>(lnincome, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb30-90"><a href="#cb30-90" aria-hidden="true" tabindex="-1"></a>    <span class="at">retprice    =</span> <span class="fu">mean</span>(retprice, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb30-91"><a href="#cb30-91" aria-hidden="true" tabindex="-1"></a>    <span class="at">age15to24   =</span> <span class="fu">mean</span>(age15to24, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb30-92"><a href="#cb30-92" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb30-93"><a href="#cb30-93" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2b. beer is sparser, so use a narrower window where data is densest.</span></span>
<span id="cb30-94"><a href="#cb30-94" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate_predictor</span>(<span class="at">time_window =</span> <span class="dv">1984</span><span class="sc">:</span><span class="dv">1988</span>,</span>
<span id="cb30-95"><a href="#cb30-95" aria-hidden="true" tabindex="-1"></a>                     <span class="at">beer =</span> <span class="fu">mean</span>(beer, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb30-96"><a href="#cb30-96" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2c. Three "lagged outcomes" - cigsale at three pre-period dates.</span></span>
<span id="cb30-97"><a href="#cb30-97" aria-hidden="true" tabindex="-1"></a>  <span class="co">#     These pin synthetic California's pre-period trajectory.</span></span>
<span id="cb30-98"><a href="#cb30-98" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate_predictor</span>(<span class="at">time_window =</span> <span class="dv">1975</span>, <span class="at">cigsale_1975 =</span> cigsale) <span class="sc">|&gt;</span></span>
<span id="cb30-99"><a href="#cb30-99" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate_predictor</span>(<span class="at">time_window =</span> <span class="dv">1980</span>, <span class="at">cigsale_1980 =</span> cigsale) <span class="sc">|&gt;</span></span>
<span id="cb30-100"><a href="#cb30-100" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate_predictor</span>(<span class="at">time_window =</span> <span class="dv">1988</span>, <span class="at">cigsale_1988 =</span> cigsale) <span class="sc">|&gt;</span></span>
<span id="cb30-101"><a href="#cb30-101" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3. Solve the constrained QP for donor weights w*. The three IPOP</span></span>
<span id="cb30-102"><a href="#cb30-102" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    parameters are tuning knobs for the interior-point optimiser.</span></span>
<span id="cb30-103"><a href="#cb30-103" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate_weights</span>(<span class="at">optimization_window =</span> <span class="dv">1970</span><span class="sc">:</span><span class="dv">1988</span>,</span>
<span id="cb30-104"><a href="#cb30-104" aria-hidden="true" tabindex="-1"></a>                   <span class="at">margin_ipop =</span> .<span class="dv">02</span>,</span>
<span id="cb30-105"><a href="#cb30-105" aria-hidden="true" tabindex="-1"></a>                   <span class="at">sigf_ipop   =</span> <span class="dv">7</span>,</span>
<span id="cb30-106"><a href="#cb30-106" aria-hidden="true" tabindex="-1"></a>                   <span class="at">bound_ipop  =</span> <span class="dv">6</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-107"><a href="#cb30-107" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 4. Compute the synthetic California series from w* and donor outcomes.</span></span>
<span id="cb30-108"><a href="#cb30-108" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate_control</span>()</span>
<span id="cb30-109"><a href="#cb30-109" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-110"><a href="#cb30-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-111"><a href="#cb30-111" aria-hidden="true" tabindex="-1"></a>**Predictor choices.** Seven predictors are passed in. Three are pre-period covariate averages over the full pre-period (<span class="in">`lnincome`</span>, <span class="in">`retprice`</span>, <span class="in">`age15to24`</span> over 1980–1988). One uses a narrower window where data is densest (<span class="in">`beer`</span> over 1984–1988). Three are *lagged outcomes* — cigarette sales themselves at 1975, 1980, and 1988. The lagged outcomes are the most important trick: anchoring the synthetic control on the treated unit's own pre-period *outcome levels* at multiple time points forces the synthetic series to track California's pre-1988 trajectory closely.</span>
<span id="cb30-112"><a href="#cb30-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-113"><a href="#cb30-113" aria-hidden="true" tabindex="-1"></a><span class="fu">## Donor weights and predictor weights</span></span>
<span id="cb30-114"><a href="#cb30-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-115"><a href="#cb30-115" aria-hidden="true" tabindex="-1"></a>The optimisation produces two weight vectors that drive the entire fit. Both are extractable as tidy tables.</span>
<span id="cb30-116"><a href="#cb30-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-119"><a href="#cb30-119" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-120"><a href="#cb30-120" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: donor-weights</span></span>
<span id="cb30-121"><a href="#cb30-121" aria-hidden="true" tabindex="-1"></a><span class="fu">grab_unit_weights</span>(prop99_syn) <span class="sc">|&gt;</span></span>
<span id="cb30-122"><a href="#cb30-122" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(weight)) <span class="sc">|&gt;</span></span>
<span id="cb30-123"><a href="#cb30-123" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">8</span>)</span>
<span id="cb30-124"><a href="#cb30-124" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-125"><a href="#cb30-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-128"><a href="#cb30-128" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-129"><a href="#cb30-129" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: predictor-weights</span></span>
<span id="cb30-130"><a href="#cb30-130" aria-hidden="true" tabindex="-1"></a><span class="fu">grab_predictor_weights</span>(prop99_syn) <span class="sc">|&gt;</span></span>
<span id="cb30-131"><a href="#cb30-131" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(weight))</span>
<span id="cb30-132"><a href="#cb30-132" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-133"><a href="#cb30-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-134"><a href="#cb30-134" aria-hidden="true" tabindex="-1"></a>Two things to notice.</span>
<span id="cb30-135"><a href="#cb30-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-136"><a href="#cb30-136" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Five states absorb essentially 100% of the donor weight.** Utah, Nevada, Montana, Colorado, Connecticut. Every other state gets effectively zero. California is matched mostly to other Western/sunbelt states with similar age structure and cigarette price levels, plus Connecticut as a smoking-rate counterweight from the east.</span>
<span id="cb30-137"><a href="#cb30-137" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**The two earliest cigsale levels dominate the V matrix.** <span class="in">`cigsale_1975`</span> and <span class="in">`cigsale_1980`</span> together get roughly 88% of the predictor weight. The four behavioural and demographic covariates get less than 9% combined. The optimiser has effectively decided: "the best way to predict California's cigarette sales is using *other states' cigarette sales*."</span>
<span id="cb30-138"><a href="#cb30-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-139"><a href="#cb30-139" aria-hidden="true" tabindex="-1"></a>For a one-line visual of both weight vectors, tidysynth ships a <span class="in">`plot_weights()`</span> helper:</span>
<span id="cb30-140"><a href="#cb30-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-143"><a href="#cb30-143" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-144"><a href="#cb30-144" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-sc-weights</span></span>
<span id="cb30-145"><a href="#cb30-145" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Donor unit weights (left) and predictor V-matrix weights (right) from tidysynth."</span></span>
<span id="cb30-146"><a href="#cb30-146" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 9</span></span>
<span id="cb30-147"><a href="#cb30-147" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb30-148"><a href="#cb30-148" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_weights</span>(prop99_syn)</span>
<span id="cb30-149"><a href="#cb30-149" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-150"><a href="#cb30-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-151"><a href="#cb30-151" aria-hidden="true" tabindex="-1"></a><span class="fu">### A closer look at the V matrix</span></span>
<span id="cb30-152"><a href="#cb30-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-153"><a href="#cb30-153" aria-hidden="true" tabindex="-1"></a>The combined <span class="in">`plot_weights()`</span> view is convenient, but the V matrix deserves a stand-alone chart because it answers a different question than the donor weights. Donor weights say *which states* mimic California; the V matrix says *which variables* the optimiser used to decide what "mimics" means.</span>
<span id="cb30-154"><a href="#cb30-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-157"><a href="#cb30-157" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-158"><a href="#cb30-158" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-sc-predictor-weights</span></span>
<span id="cb30-159"><a href="#cb30-159" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "V matrix: cigsale_1975 and cigsale_1980 dominate; behavioural covariates get nearly zero weight."</span></span>
<span id="cb30-160"><a href="#cb30-160" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb30-161"><a href="#cb30-161" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 4</span></span>
<span id="cb30-162"><a href="#cb30-162" aria-hidden="true" tabindex="-1"></a>predw_df <span class="ot">&lt;-</span> <span class="fu">grab_predictor_weights</span>(prop99_syn) <span class="sc">|&gt;</span></span>
<span id="cb30-163"><a href="#cb30-163" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="fu">fct_reorder</span>(variable, weight))</span>
<span id="cb30-164"><a href="#cb30-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-165"><a href="#cb30-165" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(predw_df, <span class="fu">aes</span>(<span class="at">x =</span> weight, <span class="at">y =</span> variable)) <span class="sc">+</span></span>
<span id="cb30-166"><a href="#cb30-166" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"#6a9bcc"</span>) <span class="sc">+</span></span>
<span id="cb30-167"><a href="#cb30-167" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, weight)), <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.12</span>) <span class="sc">+</span></span>
<span id="cb30-168"><a href="#cb30-168" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))) <span class="sc">+</span></span>
<span id="cb30-169"><a href="#cb30-169" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"V-matrix weight (predictor importance)"</span>, <span class="at">y =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb30-170"><a href="#cb30-170" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb30-171"><a href="#cb30-171" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-172"><a href="#cb30-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-173"><a href="#cb30-173" aria-hidden="true" tabindex="-1"></a>Two readings of the same picture, one practical and one cautionary.</span>
<span id="cb30-174"><a href="#cb30-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-175"><a href="#cb30-175" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>*Practical reading.* Two lagged outcomes (`cigsale_1975` and `cigsale_1980`) carry the bulk of the matching information. The optimiser has decided that California's pre-period cigarette sales — *at multiple time points* — are the best fingerprint to match.</span>
<span id="cb30-176"><a href="#cb30-176" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>*Cautionary reading.* The V matrix is **not a causal ranking**. It tells you which variables were *useful for matching the treated unit's pre-period*, not which variables *cause* the outcome.</span>
<span id="cb30-177"><a href="#cb30-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-178"><a href="#cb30-178" aria-hidden="true" tabindex="-1"></a>**Common pitfall.** Treating the V matrix as a list of causal drivers. It is a list of *good pre-period predictors for one specific unit*, not a structural model of smoking.</span>
<span id="cb30-179"><a href="#cb30-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-180"><a href="#cb30-180" aria-hidden="true" tabindex="-1"></a><span class="fu">## The estimate</span></span>
<span id="cb30-181"><a href="#cb30-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-184"><a href="#cb30-184" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-185"><a href="#cb30-185" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: sc-att</span></span>
<span id="cb30-186"><a href="#cb30-186" aria-hidden="true" tabindex="-1"></a><span class="co"># grab_synthetic_control() returns a tidy tibble with observed (real_y)</span></span>
<span id="cb30-187"><a href="#cb30-187" aria-hidden="true" tabindex="-1"></a><span class="co"># and synthetic (synth_y) cigsale for every year. We restrict to the</span></span>
<span id="cb30-188"><a href="#cb30-188" aria-hidden="true" tabindex="-1"></a><span class="co"># post-period and compute the per-year gap.</span></span>
<span id="cb30-189"><a href="#cb30-189" aria-hidden="true" tabindex="-1"></a>sc_post <span class="ot">&lt;-</span> <span class="fu">grab_synthetic_control</span>(prop99_syn) <span class="sc">|&gt;</span></span>
<span id="cb30-190"><a href="#cb30-190" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(time_unit <span class="sc">&gt;</span> <span class="dv">1988</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-191"><a href="#cb30-191" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dif =</span> real_y <span class="sc">-</span> synth_y)</span>
<span id="cb30-192"><a href="#cb30-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-193"><a href="#cb30-193" aria-hidden="true" tabindex="-1"></a><span class="co"># Average the per-year gap to recover the ATT.</span></span>
<span id="cb30-194"><a href="#cb30-194" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(sc_post<span class="sc">$</span>dif)</span>
<span id="cb30-195"><a href="#cb30-195" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-196"><a href="#cb30-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-197"><a href="#cb30-197" aria-hidden="true" tabindex="-1"></a>The Synthetic Control ATT is approximately **$-18.85$ packs/capita** averaged over 1989–2000. This is the book's primary causal estimate and within rounding of the canonical @abadie2010synthetic result.</span>
<span id="cb30-198"><a href="#cb30-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-201"><a href="#cb30-201" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-202"><a href="#cb30-202" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-sc-trends</span></span>
<span id="cb30-203"><a href="#cb30-203" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Synthetic Control: California (observed) vs synthetic California (weighted donor combination)."</span></span>
<span id="cb30-204"><a href="#cb30-204" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb30-205"><a href="#cb30-205" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb30-206"><a href="#cb30-206" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_trends</span>(prop99_syn)</span>
<span id="cb30-207"><a href="#cb30-207" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-208"><a href="#cb30-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-209"><a href="#cb30-209" aria-hidden="true" tabindex="-1"></a>The pre-period fit is excellent — the synthetic and observed series are nearly indistinguishable through 1988. A substantial gap opens immediately after 1989, widening to roughly 30 packs by 2000.</span>
<span id="cb30-210"><a href="#cb30-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-211"><a href="#cb30-211" aria-hidden="true" tabindex="-1"></a><span class="fu">## Predictor balance: did the matching work?</span></span>
<span id="cb30-212"><a href="#cb30-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-213"><a href="#cb30-213" aria-hidden="true" tabindex="-1"></a><span class="in">`grab_balance_table()`</span> shows California, synthetic California, and the unweighted donor average side-by-side on every predictor.</span>
<span id="cb30-214"><a href="#cb30-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-217"><a href="#cb30-217" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-218"><a href="#cb30-218" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: sc-balance</span></span>
<span id="cb30-219"><a href="#cb30-219" aria-hidden="true" tabindex="-1"></a><span class="fu">grab_balance_table</span>(prop99_syn)</span>
<span id="cb30-220"><a href="#cb30-220" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-221"><a href="#cb30-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-222"><a href="#cb30-222" aria-hidden="true" tabindex="-1"></a>On every variable, *synthetic California* is far closer to California than the unweighted donor average is. The most dramatic improvement is on the lagged outcomes: <span class="in">`cigsale_1988`</span> is roughly 90 for California vs ≈91 for the synthetic — a near-perfect match — while the unweighted donor average is around 114. That gap of ~24 packs is exactly the bias the naive pre-post method silently absorbed.</span>
<span id="cb30-223"><a href="#cb30-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-224"><a href="#cb30-224" aria-hidden="true" tabindex="-1"></a><span class="fu">## Visualising the post-period gap</span></span>
<span id="cb30-225"><a href="#cb30-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-226"><a href="#cb30-226" aria-hidden="true" tabindex="-1"></a><span class="in">`plot_trends()`</span> showed *both* observed and synthetic California on one canvas. The companion helper `plot_differences()` plots just the *gap*: $Y_{1t} - \widehat{Y_{1t}(0)}$, year by year. This isolates the treatment-effect curve in its cleanest form.</span>
<span id="cb30-227"><a href="#cb30-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-230"><a href="#cb30-230" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-231"><a href="#cb30-231" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-sc-differences</span></span>
<span id="cb30-232"><a href="#cb30-232" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Per-year gap between observed California and synthetic California."</span></span>
<span id="cb30-233"><a href="#cb30-233" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb30-234"><a href="#cb30-234" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb30-235"><a href="#cb30-235" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_differences</span>(prop99_syn)</span>
<span id="cb30-236"><a href="#cb30-236" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-237"><a href="#cb30-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-238"><a href="#cb30-238" aria-hidden="true" tabindex="-1"></a>Read the line as the *effect of Proposition 99 on California in year $t$*. The pre-period values hover near zero (the matching worked), the line drops sharply after 1989, and it stays negative — steadily widening — throughout the post-period. The 1989–2000 mean of this series is exactly the $-18.85$ packs ATT reported above.</span>
<span id="cb30-239"><a href="#cb30-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-240"><a href="#cb30-240" aria-hidden="true" tabindex="-1"></a><span class="fu">## Inference via placebo permutation</span></span>
<span id="cb30-241"><a href="#cb30-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-242"><a href="#cb30-242" aria-hidden="true" tabindex="-1"></a>A "standard error" computed as cross-year SD divided by $\sqrt{N}$ is *not* a real sampling-distribution-based standard error. The proper Synthetic Control uncertainty quantification is a permutation test.</span>
<span id="cb30-243"><a href="#cb30-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-244"><a href="#cb30-244" aria-hidden="true" tabindex="-1"></a>**The recipe.** Refit the synthetic-control model treating *each donor state* as if *it* had been the treated unit. Compute the post-period gap for each placebo. Compare California's gap trajectory to those placebo trajectories. If California's gap is extreme relative to the placebos, the policy probably did something.</span>
<span id="cb30-245"><a href="#cb30-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-248"><a href="#cb30-248" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-249"><a href="#cb30-249" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-sc-placebos</span></span>
<span id="cb30-250"><a href="#cb30-250" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Placebo permutation: California in orange, donor placebos in grey (badly pre-fit donors pruned by default)."</span></span>
<span id="cb30-251"><a href="#cb30-251" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb30-252"><a href="#cb30-252" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb30-253"><a href="#cb30-253" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_placebos</span>(prop99_syn)</span>
<span id="cb30-254"><a href="#cb30-254" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-255"><a href="#cb30-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-256"><a href="#cb30-256" aria-hidden="true" tabindex="-1"></a>The orange line is California; the grey lines are the donor placebos. By default, <span class="in">`plot_placebos()`</span> *prunes* placebos whose pre-period mean squared prediction error (MSPE) exceeds twice California's — those donors fit their own pre-period so badly that comparing their post-period gap to California's would be misleading. After pruning, California's post-period gap sits visibly below every retained placebo, which is the visual signature of a "real" treatment effect.</span>
<span id="cb30-257"><a href="#cb30-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-258"><a href="#cb30-258" aria-hidden="true" tabindex="-1"></a>The unpruned variant keeps every donor for full transparency:</span>
<span id="cb30-259"><a href="#cb30-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-262"><a href="#cb30-262" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-263"><a href="#cb30-263" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-sc-placebos-unpruned</span></span>
<span id="cb30-264"><a href="#cb30-264" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Same placebo plot with every donor retained — including badly pre-fit ones — to show the full pool of placebo trajectories."</span></span>
<span id="cb30-265"><a href="#cb30-265" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb30-266"><a href="#cb30-266" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb30-267"><a href="#cb30-267" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_placebos</span>(prop99_syn, <span class="at">prune =</span> <span class="cn">FALSE</span>)</span>
<span id="cb30-268"><a href="#cb30-268" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-269"><a href="#cb30-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-270"><a href="#cb30-270" aria-hidden="true" tabindex="-1"></a>With pruning off, the grey cloud is messier and a few badly-fit donors swing wildly — but California's post-period descent still ends up at the bottom of the bundle. The qualitative conclusion does not depend on the pruning rule.</span>
<span id="cb30-271"><a href="#cb30-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-272"><a href="#cb30-272" aria-hidden="true" tabindex="-1"></a><span class="fu">## MSPE ratio and Fisher exact p-value</span></span>
<span id="cb30-273"><a href="#cb30-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-274"><a href="#cb30-274" aria-hidden="true" tabindex="-1"></a>A sharper version of the same test is the **MSPE ratio** — the ratio of post-period to pre-period mean squared prediction error. If a unit has a tight pre-period fit *and* a large post-period gap, the ratio is large.</span>
<span id="cb30-275"><a href="#cb30-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-278"><a href="#cb30-278" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-279"><a href="#cb30-279" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: sc-significance</span></span>
<span id="cb30-280"><a href="#cb30-280" aria-hidden="true" tabindex="-1"></a><span class="co"># grab_significance() returns one row per unit (treated + every placebo)</span></span>
<span id="cb30-281"><a href="#cb30-281" aria-hidden="true" tabindex="-1"></a><span class="co"># with pre_mspe, post_mspe, the post/pre ratio, the unit's rank in that</span></span>
<span id="cb30-282"><a href="#cb30-282" aria-hidden="true" tabindex="-1"></a><span class="co"># ratio, and the Fisher-style p-value (rank / n_units).</span></span>
<span id="cb30-283"><a href="#cb30-283" aria-hidden="true" tabindex="-1"></a><span class="fu">grab_significance</span>(prop99_syn) <span class="sc">|&gt;</span></span>
<span id="cb30-284"><a href="#cb30-284" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mspe_ratio)) <span class="sc">|&gt;</span></span>
<span id="cb30-285"><a href="#cb30-285" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb30-286"><a href="#cb30-286" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-287"><a href="#cb30-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-288"><a href="#cb30-288" aria-hidden="true" tabindex="-1"></a>California's MSPE ratio is around **124** — more than two and a half times higher than the next-highest unit. California ranks **1st out of 39 units**. The Fisher exact $p$-value is rank divided by total units, so $1/39 \approx 0.026$. Under the null hypothesis that Proposition 99 had no effect, the probability of seeing a unit this extreme purely by chance is about 2.6%.</span>
<span id="cb30-289"><a href="#cb30-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-292"><a href="#cb30-292" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-293"><a href="#cb30-293" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-sc-mspe-ratio</span></span>
<span id="cb30-294"><a href="#cb30-294" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "MSPE-ratio bar chart with California highlighted at rank 1 out of 39 units."</span></span>
<span id="cb30-295"><a href="#cb30-295" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb30-296"><a href="#cb30-296" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb30-297"><a href="#cb30-297" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_mspe_ratio</span>(prop99_syn)</span>
<span id="cb30-298"><a href="#cb30-298" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-299"><a href="#cb30-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-300"><a href="#cb30-300" aria-hidden="true" tabindex="-1"></a>The orange bar at the top is California; every blue bar below it is a placebo donor. The gap between California and the second-place state is enormous. That gap is the visual signature of "a real treatment effect that the donor pool does not naturally replicate".</span>
<span id="cb30-301"><a href="#cb30-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-302"><a href="#cb30-302" aria-hidden="true" tabindex="-1"></a><span class="fu">## Inspecting the nested tidysynth object</span></span>
<span id="cb30-303"><a href="#cb30-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-304"><a href="#cb30-304" aria-hidden="true" tabindex="-1"></a><span class="in">`prop99_syn`</span> is not a plain data frame — it is a *nested tibble* with one row per unit (treated unit + every donor refit as a placebo) and list-columns that hold every intermediate output of the optimisation.</span>
<span id="cb30-305"><a href="#cb30-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-308"><a href="#cb30-308" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-309"><a href="#cb30-309" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: sc-nested</span></span>
<span id="cb30-310"><a href="#cb30-310" aria-hidden="true" tabindex="-1"></a>prop99_syn</span>
<span id="cb30-311"><a href="#cb30-311" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-312"><a href="#cb30-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-313"><a href="#cb30-313" aria-hidden="true" tabindex="-1"></a>Each list-column can be flattened with <span class="in">`tidyr::unnest()`</span> for custom downstream work, or pulled out with one of the <span class="in">`grab_*()`</span> helpers used above.</span>
<span id="cb30-314"><a href="#cb30-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-317"><a href="#cb30-317" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-318"><a href="#cb30-318" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: sc-unnest</span></span>
<span id="cb30-319"><a href="#cb30-319" aria-hidden="true" tabindex="-1"></a><span class="co"># Flatten .outcome into a wide table: one row per (unit, year).</span></span>
<span id="cb30-320"><a href="#cb30-320" aria-hidden="true" tabindex="-1"></a><span class="co"># The actual cigarette-sales column is named after each unit, so we</span></span>
<span id="cb30-321"><a href="#cb30-321" aria-hidden="true" tabindex="-1"></a><span class="co"># select metadata + California's series for a clean preview.</span></span>
<span id="cb30-322"><a href="#cb30-322" aria-hidden="true" tabindex="-1"></a>prop99_syn <span class="sc">|&gt;</span></span>
<span id="cb30-323"><a href="#cb30-323" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest</span>(<span class="at">cols =</span> <span class="fu">c</span>(.outcome)) <span class="sc">|&gt;</span></span>
<span id="cb30-324"><a href="#cb30-324" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(.id, .placebo, .type, time_unit, California) <span class="sc">|&gt;</span></span>
<span id="cb30-325"><a href="#cb30-325" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">8</span>)</span>
<span id="cb30-326"><a href="#cb30-326" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-327"><a href="#cb30-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-328"><a href="#cb30-328" aria-hidden="true" tabindex="-1"></a>For the tidy *observed-vs-synthetic* table (which is what most analyses want), the dedicated helper is more convenient:</span>
<span id="cb30-329"><a href="#cb30-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-332"><a href="#cb30-332" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-333"><a href="#cb30-333" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: sc-unnest-tidy</span></span>
<span id="cb30-334"><a href="#cb30-334" aria-hidden="true" tabindex="-1"></a><span class="fu">grab_synthetic_control</span>(prop99_syn) <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">8</span>)</span>
<span id="cb30-335"><a href="#cb30-335" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb30-336"><a href="#cb30-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-337"><a href="#cb30-337" aria-hidden="true" tabindex="-1"></a>This is the whole point of the nested-tibble design: every step of the optimisation is *introspectable from R*, with no need to dig into S4 slots or <span class="in">`attr()`</span> blobs.</span>
<span id="cb30-338"><a href="#cb30-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-339"><a href="#cb30-339" aria-hidden="true" tabindex="-1"></a><span class="fu">## Recap</span></span>
<span id="cb30-340"><a href="#cb30-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-341"><a href="#cb30-341" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Question <span class="pp">|</span> Answer <span class="pp">|</span></span>
<span id="cb30-342"><a href="#cb30-342" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb30-343"><a href="#cb30-343" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> What does Synthetic Control estimate? <span class="pp">|</span> The ATT on California, 1989–2000 <span class="pp">|</span></span>
<span id="cb30-344"><a href="#cb30-344" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> What is the point estimate? <span class="pp">|</span> **$-18.85$ packs/capita per year** <span class="pp">|</span></span>
<span id="cb30-345"><a href="#cb30-345" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> What is "synthetic California"? <span class="pp">|</span> A convex combination of five Western/sunbelt states (Utah, Nevada, Montana, Colorado, Connecticut) <span class="pp">|</span></span>
<span id="cb30-346"><a href="#cb30-346" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> What predictors did the matching? <span class="pp">|</span> Mostly two lagged outcomes — <span class="in">`cigsale_1975`</span> and <span class="in">`cigsale_1980`</span> <span class="pp">|</span></span>
<span id="cb30-347"><a href="#cb30-347" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> How is the matching quality? <span class="pp">|</span> Excellent — synthetic and observed California are near-identical through 1988 <span class="pp">|</span></span>
<span id="cb30-348"><a href="#cb30-348" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> What is the inference statistic? <span class="pp">|</span> Fisher exact $p \approx 0.026$ (California ranks 1st out of 39 on the MSPE ratio) <span class="pp">|</span></span>
<span id="cb30-349"><a href="#cb30-349" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> What is the design-time pitfall? <span class="pp">|</span> Don't read the V matrix as a list of causal drivers — it is a list of *good pre-period predictors* <span class="pp">|</span></span>
<span id="cb30-350"><a href="#cb30-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-351"><a href="#cb30-351" aria-hidden="true" tabindex="-1"></a>Synthetic Control is the book's headline causal estimate, and the placebo / MSPE-ratio diagnostics both confirm that California's post-1989 trajectory is unusual relative to what other states experienced in the same window. In chapter 6 we hand the same donor information to a Bayesian model and ask whether a *credible interval* (a direct probability statement about the effect) tells the same story.</span>
<span id="cb30-352"><a href="#cb30-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-353"><a href="#cb30-353" aria-hidden="true" tabindex="-1"></a><span class="fu">## Further reading</span></span>
<span id="cb30-354"><a href="#cb30-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-355"><a href="#cb30-355" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>@abadie2010synthetic — the original synthetic-control treatment of Proposition 99.</span>
<span id="cb30-356"><a href="#cb30-356" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>@abadie2021using — methodological feasibility, data requirements, and assumptions in a JEL review.</span>
<span id="cb30-357"><a href="#cb30-357" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>@dunford2024tidysynth — documentation for the <span class="in">`tidysynth`</span> package used here.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/quarcs-lab/ccm/edit/main/05-classical-synthetic-control.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/quarcs-lab/ccm/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>