<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Staggered Differences-in-Differences – Comparative Causal Metrics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-bayesian-spatial-sc.html" rel="next">
<link href="./05-classical-synthetic-control.html" rel="prev">
<link href="./images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-f1aadacce99040138bbb613f9330654f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0da87e08732b0aad79cc276a1be62fe2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-c77ee8f8b07d41e0e364fbf0a2ddebb9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<meta name="mermaid-theme" content="neutral">
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="custom.css">
</head>

<body class="nav-sidebar floating quarto-dark"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = true;
    const darkModeDefault = authorPrefersDark;
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-structural-bayesian-ts.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Structural Bayesian Time Series</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Comparative Causal Metrics</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/quarcs-lab/ccm" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Comparative-Causal-Metrics.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-interrupted-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Interrupted Time Series</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-rd-in-time.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regression Discontinuity in Time</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-basic-diff-in-diff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Basic Differences-in-Differences</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-classical-synthetic-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Classical Synthetic Control</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-structural-bayesian-ts.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Structural Bayesian Time Series</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-bayesian-spatial-sc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Bayesian Spatial Synthetic Control</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-synthetic-control-prediction-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Synthetic Control with Prediction Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-staggered-did.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Staggered Differences-in-Differences</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-bsts-causalimpact-idea" id="toc-the-bsts-causalimpact-idea" class="nav-link active" data-scroll-target="#the-bsts-causalimpact-idea"><span class="header-section-number">6.1</span> The BSTS / CausalImpact idea</a></li>
  <li><a href="#the-model-in-two-pieces" id="toc-the-model-in-two-pieces" class="nav-link" data-scroll-target="#the-model-in-two-pieces"><span class="header-section-number">6.2</span> The model in two pieces</a></li>
  <li><a href="#setup-and-data" id="toc-setup-and-data" class="nav-link" data-scroll-target="#setup-and-data"><span class="header-section-number">6.3</span> Setup and data</a></li>
  <li><a href="#imputation-and-wide-pivot" id="toc-imputation-and-wide-pivot" class="nav-link" data-scroll-target="#imputation-and-wide-pivot"><span class="header-section-number">6.4</span> Imputation and wide pivot</a></li>
  <li><a href="#fit-the-bayesian-structural-ts-model" id="toc-fit-the-bayesian-structural-ts-model" class="nav-link" data-scroll-target="#fit-the-bayesian-structural-ts-model"><span class="header-section-number">6.5</span> Fit the Bayesian structural TS model</a></li>
  <li><a href="#the-two-panel-diagnostic" id="toc-the-two-panel-diagnostic" class="nav-link" data-scroll-target="#the-two-panel-diagnostic"><span class="header-section-number">6.6</span> The two-panel diagnostic</a></li>
  <li><a href="#common-pitfall" id="toc-common-pitfall" class="nav-link" data-scroll-target="#common-pitfall"><span class="header-section-number">6.7</span> Common pitfall</a></li>
  <li><a href="#recap" id="toc-recap" class="nav-link" data-scroll-target="#recap"><span class="header-section-number">6.8</span> Recap</a></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading"><span class="header-section-number">6.9</span> Further reading</a></li>
  <li><a href="#when-basic-did-breaks" id="toc-when-basic-did-breaks" class="nav-link" data-scroll-target="#when-basic-did-breaks"><span class="header-section-number">6.10</span> When Basic DiD breaks</a></li>
  <li><a href="#setup-and-data-1" id="toc-setup-and-data-1" class="nav-link" data-scroll-target="#setup-and-data-1"><span class="header-section-number">6.11</span> Setup and data</a></li>
  <li><a href="#the-twfe-baseline-and-its-problem" id="toc-the-twfe-baseline-and-its-problem" class="nav-link" data-scroll-target="#the-twfe-baseline-and-its-problem"><span class="header-section-number">6.12</span> The TWFE baseline and its problem</a>
  <ul class="collapse">
  <li><a href="#sun-abraham-event-study" id="toc-sun-abraham-event-study" class="nav-link" data-scroll-target="#sun-abraham-event-study"><span class="header-section-number">6.12.1</span> Sun-Abraham event study</a></li>
  <li><a href="#twfe-weight-decomposition" id="toc-twfe-weight-decomposition" class="nav-link" data-scroll-target="#twfe-weight-decomposition"><span class="header-section-number">6.12.2</span> TWFE weight decomposition</a></li>
  </ul></li>
  <li><a href="#group-time-atts-the-callaway-santanna-approach" id="toc-group-time-atts-the-callaway-santanna-approach" class="nav-link" data-scroll-target="#group-time-atts-the-callaway-santanna-approach"><span class="header-section-number">6.13</span> Group-time ATTs: the Callaway-Sant’Anna approach</a>
  <ul class="collapse">
  <li><a href="#aggregation-overall-att-and-event-study" id="toc-aggregation-overall-att-and-event-study" class="nav-link" data-scroll-target="#aggregation-overall-att-and-event-study"><span class="header-section-number">6.13.1</span> Aggregation: overall ATT and event study</a></li>
  </ul></li>
  <li><a href="#conditional-parallel-trends" id="toc-conditional-parallel-trends" class="nav-link" data-scroll-target="#conditional-parallel-trends"><span class="header-section-number">6.14</span> Conditional parallel trends</a></li>
  <li><a href="#robustness-knobs" id="toc-robustness-knobs" class="nav-link" data-scroll-target="#robustness-knobs"><span class="header-section-number">6.15</span> Robustness knobs</a></li>
  <li><a href="#sensitivity-to-parallel-trends-violations" id="toc-sensitivity-to-parallel-trends-violations" class="nav-link" data-scroll-target="#sensitivity-to-parallel-trends-violations"><span class="header-section-number">6.16</span> Sensitivity to parallel-trends violations</a></li>
  <li><a href="#heterogeneous-treatment-doses" id="toc-heterogeneous-treatment-doses" class="nav-link" data-scroll-target="#heterogeneous-treatment-doses"><span class="header-section-number">6.17</span> Heterogeneous treatment doses</a></li>
  <li><a href="#lagged-outcomes-an-alternative-identifying-assumption" id="toc-lagged-outcomes-an-alternative-identifying-assumption" class="nav-link" data-scroll-target="#lagged-outcomes-an-alternative-identifying-assumption"><span class="header-section-number">6.18</span> Lagged outcomes: an alternative identifying assumption</a></li>
  <li><a href="#recap-1" id="toc-recap-1" class="nav-link" data-scroll-target="#recap-1"><span class="header-section-number">6.19</span> Recap</a></li>
  <li><a href="#common-pitfall-1" id="toc-common-pitfall-1" class="nav-link" data-scroll-target="#common-pitfall-1"><span class="header-section-number">6.20</span> Common pitfall</a></li>
  <li><a href="#further-reading-1" id="toc-further-reading-1" class="nav-link" data-scroll-target="#further-reading-1"><span class="header-section-number">6.21</span> Further reading</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">6.22</span> Exercises</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/quarcs-lab/ccm/edit/main/06-structural-bayesian-ts.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/quarcs-lab/ccm/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Staggered Differences-in-Differences</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="the-bsts-causalimpact-idea" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="the-bsts-causalimpact-idea"><span class="header-section-number">6.1</span> The BSTS / CausalImpact idea</h2>
<p>Fit a <strong>Bayesian structural time-series (BSTS)</strong> model on the pre-period. Use <em>other states’ cigarette sales</em> (and optionally covariates) as predictors. Project the fitted model forward as the counterfactual. The posterior over (observed − projected) gives a credible interval for the policy effect.</p>
<p>This is the only method in the book that delivers a <em>credible</em> interval — a direct probability statement about the parameter — rather than a frequentist confidence band or a Fisher exact <span class="math inline">\(p\)</span>-value.</p>
</section>
<section id="the-model-in-two-pieces" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="the-model-in-two-pieces"><span class="header-section-number">6.2</span> The model in two pieces</h2>
<p>The BSTS counterfactual is</p>
<p><span class="math display">\[y_{1t} = \mu_t + \beta^\top x_t + \varepsilon_t, \quad t \le t^*\]</span></p>
<p>where <span class="math inline">\(\mu_t\)</span> is a local-level trend, <span class="math inline">\(x_t\)</span> are the control-series regressors (other states’ <code>cigsale</code>, plus optional covariates), and <span class="math inline">\(t^*\)</span> is the intervention date. California’s outcome is <em>a slowly-evolving trend</em> <strong>plus</strong> <em>a linear combination of donor-state series</em> <strong>plus</strong> <em>a random error</em>.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-bsts-counterfactual" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bsts-counterfactual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-bsts-counterfactual">flowchart TB
    subgraph "BSTS counterfactual ŷ₁ₜ"
        TREND["μₜ — local-level trend&lt;br/&gt;(absorbs dynamics no control can explain)"]
        REG["β·xₜ — regression on donor cigsale + covariates&lt;br/&gt;(borrows from donor pool)"]
        ERR["εₜ — random error"]
    end
    TREND --&gt; Y["ŷ₁ₜ"]
    REG --&gt; Y
    ERR --&gt; Y
    Y --&gt; CMP["Observed y₁ₜ − ŷ₁ₜ&lt;br/&gt;= policy effect (with credible band)"]

    style TREND fill:#6a9bcc,stroke:#cbd5e0,color:#fff
    style REG fill:#00d4c8,stroke:#cbd5e0,color:#141413
    style ERR fill:#7a8395,stroke:#cbd5e0,color:#fff
    style Y fill:#7A209F,stroke:#cbd5e0,color:#fff
    style CMP fill:#d97757,stroke:#cbd5e0,color:#fff
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bsts-counterfactual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Decomposition of the BSTS counterfactual: a local-level trend, a regression on donor cigsale + covariates, and random error sum to ŷ₁ₜ, which is then subtracted from the observed series to give the policy effect.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The trend <span class="math inline">\(\mu_t\)</span> absorbs the dynamics that no control series can explain; the regression term <span class="math inline">\(\beta^\top x_t\)</span> borrows information from the donor pool. After the model is fit on <span class="math inline">\(t \le t^*\)</span>, it is projected forward and the posterior over <span class="math inline">\(y_{1t} - \hat{y}_{1t}\)</span> gives the credible interval for the policy effect.</p>
</section>
<section id="setup-and-data" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="setup-and-data"><span class="header-section-number">6.3</span> Setup and data</h2>
<p><strong>Packages.</strong> <code>tidyverse</code> covers wrangling and plotting. <code>CausalImpact</code> is Google’s wrapper around the <code>bsts</code> (Bayesian Structural Time Series) package: it takes a wide matrix with the treated outcome in column 1 and donor series in the remaining columns, fits a Bayesian state-space model on the pre-period, projects forward as the counterfactual, and returns posterior means + 95% credible intervals on the pointwise and cumulative effects. <code>mice</code> provides multiple imputation by chained equations — we use its random-forest mode to fill the missing covariate values before pivoting to wide form. The <code>R/table_helpers.R</code> helper provides <code>gt_pretty()</code> for the summary table.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(CausalImpact)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"R/table_helpers.R"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">dev.args =</span> <span class="fu">list</span>(<span class="at">bg =</span> <span class="st">"transparent"</span>))</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.background  =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">"#94a3b8"</span>, <span class="at">linewidth =</span> <span class="fl">0.25</span>),</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">panel.grid.minor =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">"#94a3b8"</span>, <span class="at">linewidth =</span> <span class="fl">0.15</span>),</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">text             =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#94a3b8"</span>),</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text        =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#94a3b8"</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>Dataset.</strong> Like Synthetic Control, this method uses the <strong>full 39-state × 31-year panel</strong>: every state other than California is potentially a regressor in the Bayesian counterfactual model, and the four covariates (<code>lnincome</code>, <code>retprice</code>, <code>age15to24</code>, <code>beer</code>) are candidate predictors too. We do not pre-filter or restrict the window. The dataset is loaded as-is and then reshaped from long to wide in the next section, which is the form <code>CausalImpact</code> requires.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>prop99 <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/proposition99.rds"</span>) <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The loaded <code>prop99</code> is the same 1,209-row × 7-column tibble used in chapter 5 (39 states × 31 years × the <code>cigsale</code> outcome and four covariates). The next section deals with the missing covariate values and the long-to-wide reshape that CausalImpact requires.</p>
</section>
<section id="imputation-and-wide-pivot" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="imputation-and-wide-pivot"><span class="header-section-number">6.4</span> Imputation and wide pivot</h2>
<p>CausalImpact wants a <em>wide</em> dataset with the treated outcome in column 1 and every control series in the remaining columns. The covariate columns have missing values (<code>lnincome</code> is missing 16% of rows, <code>age15to24</code> 32%, <code>beer</code> 55%), so we fill them with single random-forest imputation from <code>mice</code>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fill in missing covariate values with one round of random-forest</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># multiple imputation (m = 1, method = "rf"). printFlag suppresses</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># console chatter.</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>prop99_imputed <span class="ot">&lt;-</span> prop99 <span class="sc">|&gt;</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mice</span>(<span class="at">m =</span> <span class="dv">1</span>, <span class="at">method =</span> <span class="st">"rf"</span>, <span class="at">printFlag =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">complete</span>() <span class="sc">|&gt;</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>()</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Pivot the long panel to wide format: one column per (variable, state)</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># pair. CausalImpact requires the treated outcome in column 1, hence</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># relocate(cigsale_California) and drop the year index.</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>prop99_wide <span class="ot">&lt;-</span> prop99_imputed <span class="sc">|&gt;</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from  =</span> state,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> <span class="fu">c</span>(cigsale, lnincome, beer, age15to24, retprice)) <span class="sc">|&gt;</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(cigsale_California) <span class="sc">|&gt;</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>year)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(prop99_wide)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  31 195</code></pre>
</div>
</div>
<p>The reported <code>dim()</code> confirms the reshape: <code>prop99_wide</code> is <strong>31 rows × 195 columns</strong> — one row per year 1970–2000, and 39 states × 5 variables in the columns (<code>cigsale_*</code>, <code>lnincome_*</code>, <code>beer_*</code>, <code>age15to24_*</code>, <code>retprice_*</code> for each of the 39 states), with <code>year</code> dropped and <code>cigsale_California</code> relocated to column 1 because that’s what <code>CausalImpact()</code> expects as the treated outcome.</p>
</section>
<section id="fit-the-bayesian-structural-ts-model" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="fit-the-bayesian-structural-ts-model"><span class="header-section-number">6.5</span> Fit the Bayesian structural TS model</h2>
<p><strong>The fit.</strong> The chunk below calls <code>CausalImpact(prop99_wide, pre.period, post.period)</code> with the pre and post windows expressed as <em>integer row indices</em> (not years): row 1 is 1970, row 19 is 1988 (the last pre-period year), row 20 is 1989, row 31 is 2000. The seed is reset just before the call because <code>bsts</code> uses an MCMC sampler under the hood; a fixed seed makes the posterior draws reproducible from one render to the next. The returned <code>impact_full$summary</code> is a two-row data frame — one row for the <em>average</em> effect over 1989–2000 and one row for the <em>cumulative</em> effect — with posterior means and 95% credible bounds for each. The helper code below the <code>CausalImpact()</code> call just formats those columns into the table.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># CausalImpact takes integer row indices, not years.</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Row 1 = 1970, row 19 = 1988 (last pre-period year).</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Row 20 = 1989, row 31 = 2000 (last observed year).</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>pre_idx  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">19</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>post_idx <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">31</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Reset the seed so the BSTS MCMC draws are reproducible.</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>impact_full <span class="ot">&lt;-</span> <span class="fu">CausalImpact</span>(prop99_wide,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>                            <span class="at">pre.period  =</span> pre_idx,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>                            <span class="at">post.period =</span> post_idx)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>ci_summary <span class="ot">&lt;-</span> impact_full<span class="sc">$</span>summary <span class="sc">|&gt;</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">rownames_to_column</span>(<span class="st">"Horizon"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">transmute</span>(</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    Horizon,</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">Actual            =</span> <span class="fu">sprintf</span>(<span class="st">"%.1f"</span>, Actual),</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">Prediction        =</span> <span class="fu">sprintf</span>(<span class="st">"%.1f [%.1f, %.1f]"</span>,</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>                                Pred, Pred.lower, Pred.upper),</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Absolute effect</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sprintf</span>(<span class="st">"%.1f [%.1f, %.1f]"</span>,</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>                                AbsEffect, AbsEffect.lower, AbsEffect.upper),</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Relative effect</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sprintf</span>(<span class="st">"%.1f%% [%.1f%%, %.1f%%]"</span>,</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>                                RelEffect <span class="sc">*</span> <span class="dv">100</span>, RelEffect.lower <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>                                RelEffect.upper <span class="sc">*</span> <span class="dv">100</span>),</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Posterior p</span><span class="st">`</span>     <span class="ot">=</span> <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, p)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="fu">gt_pretty</span>(ci_summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-causalimpact" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-causalimpact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: CausalImpact posterior summary; brackets are 95% credible intervals.
</figcaption>
<div aria-describedby="tbl-causalimpact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="sttvkksdnq" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#sttvkksdnq table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#sttvkksdnq thead, #sttvkksdnq tbody, #sttvkksdnq tfoot, #sttvkksdnq tr, #sttvkksdnq td, #sttvkksdnq th {
  border-style: none;
}

#sttvkksdnq p {
  margin: 0;
  padding: 0;
}

#sttvkksdnq .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 0.95em;
  font-weight: normal;
  font-style: normal;
  background-color: rgba(255, 255, 255, 0);
  width: auto;
  border-top-style: hidden;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: hidden;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#sttvkksdnq .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#sttvkksdnq .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: rgba(255, 255, 255, 0);
  border-bottom-width: 0;
}

#sttvkksdnq .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: rgba(255, 255, 255, 0);
  border-top-width: 0;
}

#sttvkksdnq .gt_heading {
  background-color: rgba(255, 255, 255, 0);
  text-align: center;
  border-bottom-color: rgba(255, 255, 255, 0);
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#sttvkksdnq .gt_bottom_border {
  border-bottom-style: hidden;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#sttvkksdnq .gt_col_headings {
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 1px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#sttvkksdnq .gt_col_heading {
  color: #333333;
  background-color: rgba(255, 255, 255, 0);
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#sttvkksdnq .gt_column_spanner_outer {
  color: #333333;
  background-color: rgba(255, 255, 255, 0);
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#sttvkksdnq .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#sttvkksdnq .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#sttvkksdnq .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 1px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#sttvkksdnq .gt_spanner_row {
  border-bottom-style: hidden;
}

#sttvkksdnq .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: rgba(255, 255, 255, 0);
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#sttvkksdnq .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: rgba(255, 255, 255, 0);
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#sttvkksdnq .gt_from_md > :first-child {
  margin-top: 0;
}

#sttvkksdnq .gt_from_md > :last-child {
  margin-bottom: 0;
}

#sttvkksdnq .gt_row {
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: none;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#sttvkksdnq .gt_stub {
  color: #333333;
  background-color: rgba(255, 255, 255, 0);
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#sttvkksdnq .gt_stub_row_group {
  color: #333333;
  background-color: rgba(255, 255, 255, 0);
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#sttvkksdnq .gt_row_group_first td {
  border-top-width: 2px;
}

#sttvkksdnq .gt_row_group_first th {
  border-top-width: 2px;
}

#sttvkksdnq .gt_summary_row {
  color: #333333;
  background-color: rgba(255, 255, 255, 0);
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#sttvkksdnq .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#sttvkksdnq .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#sttvkksdnq .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#sttvkksdnq .gt_grand_summary_row {
  color: #333333;
  background-color: rgba(255, 255, 255, 0);
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#sttvkksdnq .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#sttvkksdnq .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#sttvkksdnq .gt_striped {
  background-color: rgba(127, 127, 127, 0.06);
}

#sttvkksdnq .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#sttvkksdnq .gt_footnotes {
  color: #333333;
  background-color: rgba(255, 255, 255, 0);
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#sttvkksdnq .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#sttvkksdnq .gt_sourcenotes {
  color: #333333;
  background-color: rgba(255, 255, 255, 0);
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#sttvkksdnq .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#sttvkksdnq .gt_left {
  text-align: left;
}

#sttvkksdnq .gt_center {
  text-align: center;
}

#sttvkksdnq .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#sttvkksdnq .gt_font_normal {
  font-weight: normal;
}

#sttvkksdnq .gt_font_bold {
  font-weight: bold;
}

#sttvkksdnq .gt_font_italic {
  font-style: italic;
}

#sttvkksdnq .gt_super {
  font-size: 65%;
}

#sttvkksdnq .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#sttvkksdnq .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#sttvkksdnq .gt_indent_1 {
  text-indent: 5px;
}

#sttvkksdnq .gt_indent_2 {
  text-indent: 10px;
}

#sttvkksdnq .gt_indent_3 {
  text-indent: 15px;
}

#sttvkksdnq .gt_indent_4 {
  text-indent: 20px;
}

#sttvkksdnq .gt_indent_5 {
  text-indent: 25px;
}

#sttvkksdnq .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#sttvkksdnq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="Horizon" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Horizon</th>
<th id="Actual" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Actual</th>
<th id="Prediction" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Prediction</th>
<th id="Absolute-effect" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Absolute effect</th>
<th id="Relative-effect" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Relative effect</th>
<th id="Posterior-p" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Posterior p</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Horizon">Average</td>
<td class="gt_row gt_right" headers="Actual">60.4</td>
<td class="gt_row gt_left" headers="Prediction">73.2 [54.7, 92.3]</td>
<td class="gt_row gt_left" headers="Absolute effect">-12.8 [-31.9, 5.7]</td>
<td class="gt_row gt_left" headers="Relative effect">-15.9% [-34.6%, 10.4%]</td>
<td class="gt_row gt_right" headers="Posterior p">0.082</td>
</tr>
<tr class="even">
<td class="gt_row gt_left gt_striped" headers="Horizon">Cumulative</td>
<td class="gt_row gt_right gt_striped" headers="Actual">724.2</td>
<td class="gt_row gt_left gt_striped" headers="Prediction">878.1 [656.1, 1107.6]</td>
<td class="gt_row gt_left gt_striped" headers="Absolute effect">-153.9 [-383.4, 68.1]</td>
<td class="gt_row gt_left gt_striped" headers="Relative effect">-15.9% [-34.6%, 10.4%]</td>
<td class="gt_row gt_right gt_striped" headers="Posterior p">0.082</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Reading the output.</strong></p>
<ul>
<li><strong>Average ATT:</strong> approximately <span class="math inline">\(-13\)</span> packs/capita (posterior SD ≈ 11), 95% credible interval roughly <span class="math inline">\([-32, +5.7]\)</span>.</li>
<li><strong>Cumulative effect:</strong> about <span class="math inline">\(-154\)</span> packs over 12 years, or roughly 16% of what would have been expected absent the policy.</li>
<li><strong>Posterior probability of any causal effect:</strong> ≈ 92%.</li>
</ul>
<p>If we drop the covariates and use only other states’ cigarette sales as controls, the point estimate strengthens to around <span class="math inline">\(-21\)</span> packs and the posterior probability rises to ≈ 97%. The covariates absorb some of the variation the simpler model was attributing to Proposition 99 — which can be read as either “added robustness” or “watered-down signal” depending on how much you trust the imputed beer-and-income covariates.</p>
</section>
<section id="the-two-panel-diagnostic" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="the-two-panel-diagnostic"><span class="header-section-number">6.6</span> The two-panel diagnostic</h2>
<p><strong>What to look for.</strong> Calling <code>plot()</code> on a <code>CausalImpact</code> object returns its default two-panel figure: the <strong>top panel</strong> shows observed California (solid line) against the Bayesian counterfactual (dashed) with its 95% credible band; the <strong>bottom panel</strong> shows the <em>cumulative</em> gap — the running sum of <code>observed − counterfactual</code> from the intervention date onwards, with its own credible band. Read the top panel for whether and when the policy effect opens up, and the bottom panel for whether the cumulative effect’s credible band excludes zero by the end of the series.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(impact_full)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-causalimpact" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-causalimpact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-structural-bayesian-ts_files/figure-html/fig-causalimpact-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-causalimpact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: CausalImpact two-panel: pointwise observed vs Bayesian counterfactual, and cumulative effect over time.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The top panel shows the pointwise picture: observed California opens a steady gap below the Bayesian counterfactual starting in 1989, with a 95% credible band that widens as we forecast further from the training window. The bottom panel cumulates that gap over time. By 2000 the cumulative effect is roughly <span class="math inline">\(-150\)</span> packs/capita with a credible interval that includes zero only at the very upper edge.</p>
</section>
<section id="common-pitfall" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="common-pitfall"><span class="header-section-number">6.7</span> Common pitfall</h2>
<p>Imputing missing covariates without thinking about the imputation model. The random-forest fill we use here is a single-imputation shortcut for tutorial speed. With multiple imputation (<span class="math inline">\(m &gt; 1\)</span>) or a different model, the estimate can move by 1–3 packs. Two concrete failure modes are worth spelling out, because they affect the credibility of the headline number rather than just its width.</p>
<p><strong>Example 1 — Imputing donor covariates with a model that “sees” California.</strong> Our <code>mice(prop99, ...)</code> call passes the entire panel — California rows included — into the imputation model. For this dataset, with only four covariates and most missingness clustered in <code>beer</code> (≈55%) and <code>age15to24</code> (≈32%) on donor states, the consequence is usually mild. But if you were to feed the <em>full panel with the post-period California outcome attached</em> into an imputer that also uses <code>cigsale</code> as a predictor, the imputer could learn from California’s post-1989 trajectory and propagate that information back into donor states’ missing covariate cells. CausalImpact would then build a counterfactual that mechanically tracks California’s post-period — biasing the estimated effect <em>toward zero</em> by construction. The safe pattern is to impute donor covariates <em>before</em> the treated outcome is in scope, or to drop the treated unit from the imputer entirely and impute donors only.</p>
<p><strong>Example 2 — Single (<code>m = 1</code>) vs multiple (<code>m = 5</code>) imputation.</strong> Single imputation treats the imputed values as if they were observed, then propagates that pretend-observed dataset through <code>CausalImpact</code>. The posterior credible band you get back is the model’s uncertainty <em>given</em> the imputed cells — it knows nothing about the uncertainty <em>introduced by the imputation itself</em>. With proper multiple imputation (<code>mice(..., m = 5)</code> and Rubin’s-rules pooling across the five resulting fits), the credible band widens by roughly 1–3 packs on this dataset because the across-imputation variance is added to the within-imputation variance. The point estimate barely moves; the interval does. For a tutorial we keep <code>m = 1</code> for speed and clarity, but a published number should use <code>m ≥ 5</code> and report a pooled estimate.</p>
</section>
<section id="recap" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="recap"><span class="header-section-number">6.8</span> Recap</h2>
<p>CausalImpact lands at <span class="math inline">\(-13\)</span> to <span class="math inline">\(-21\)</span> packs depending on whether covariates are included, with a 92–97% posterior probability of a non-zero effect. It is the only method in the book that delivers a <em>credible</em> interval (a direct probability statement about the parameter), not a frequentist confidence band.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Question</th>
<th>Answer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>What does CausalImpact estimate?</td>
<td>The ATT on California, 1989–2000</td>
</tr>
<tr class="even">
<td>What is the point estimate?</td>
<td>Average ≈ <span class="math inline">\(-13\)</span> packs/capita; cumulative ≈ <span class="math inline">\(-154\)</span> packs over 12 years</td>
</tr>
<tr class="odd">
<td>What is the uncertainty quantification?</td>
<td>95% Bayesian credible interval ≈ <span class="math inline">\([-32, +5.7]\)</span> packs; posterior probability of any effect ≈ 92%</td>
</tr>
<tr class="even">
<td>How is the counterfactual built?</td>
<td>Local-level trend + Bayesian regression on donor-state cigarette sales (+ imputed covariates)</td>
</tr>
<tr class="odd">
<td>What is the design-time pitfall?</td>
<td>Single-imputation shortcuts on covariates with high missingness; never impute donors using the treated unit</td>
</tr>
</tbody>
</table>
</section>
<section id="further-reading" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="further-reading"><span class="header-section-number">6.9</span> Further reading</h2>
<ul>
<li><span class="citation" data-cites="brodersen2015inferring">Brodersen et al. (<a href="references.html#ref-brodersen2015inferring" role="doc-biblioref">2015</a>)</span> — the original <code>CausalImpact</code> paper.</li>
<li><span class="citation" data-cites="brodersen-causalimpact-talk">Brodersen (<a href="references.html#ref-brodersen-causalimpact-talk" role="doc-biblioref">n.d.</a>)</span> — a 50-minute walk-through of the CausalImpact intuition by the package’s lead author.</li>
<li><span class="citation" data-cites="causalimpact-pkg">Brodersen &amp; Hauser (<a href="references.html#ref-causalimpact-pkg" role="doc-biblioref">n.d.</a>)</span> — package documentation and worked examples.</li>
</ul>


<!-- -->

</section>
<section id="when-basic-did-breaks" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="when-basic-did-breaks"><span class="header-section-number">6.10</span> When Basic DiD breaks</h2>
<p>Chapter 4 ran a textbook 2×2 DiD on Proposition 99, with California treated in 1989 and Nevada as the single hand-picked control. The estimate collapsed to roughly <span class="math inline">\(-5.7\)</span> packs per capita and could not be distinguished from zero. The diagnosis there was that Nevada is geographically and culturally adjacent to California and absorbs the same secular forces — so its post-1988 decline soaks up most of what we wanted to attribute to the policy.</p>
<p>There is a deeper structural problem too. Real policy data rarely has just one treated unit and one clean control unit, both treated at the same instant. States and counties <strong>adopt at different times</strong> — some in 2004, others in 2006, still others never. The natural extension of the chapter 4 model to that setting is <em>two-way fixed effects (TWFE)</em> regression:</p>
<p><span class="math display">\[y_{it} = \alpha_i + \gamma_t + \beta \cdot \text{post}_{it} + \varepsilon_{it}.\]</span></p>
<p>For two decades this was the default. We now know it is biased in the presence of staggered adoption: already-treated units silently act as <em>controls</em> for later-treated units, contaminating the contrast. The “DiD coefficient” <span class="math inline">\(\hat\beta\)</span> becomes a weighted average of group-time ATTs with <strong>some negative weights</strong> <span class="citation" data-cites="goodmanbacon2021difference dechaisemartin2020twoway">(<a href="references.html#ref-dechaisemartin2020twoway" role="doc-biblioref">Chaisemartin &amp; D’Haultfœuille, 2020</a>; <a href="references.html#ref-goodmanbacon2021difference" role="doc-biblioref">Goodman-Bacon, 2021</a>)</span>. When treatment effects grow over time — the textbook policy story — those negative weights can flip the sign of <span class="math inline">\(\hat\beta\)</span> relative to any sensible average effect.</p>
<p>This chapter walks through the modern toolkit for repairing that damage. The methods build on <span class="citation" data-cites="callaway2021difference">Callaway &amp; Sant’Anna (<a href="references.html#ref-callaway2021difference" role="doc-biblioref">2021</a>)</span>: estimate <strong>group-time average treatment effects</strong> <span class="math inline">\(ATT(g, t)\)</span> directly, then aggregate them with weights you can defend. Along the way we look at three companion ideas: the Sun-Abraham interaction-weighted event study <span class="citation" data-cites="sun2021estimating">(<a href="references.html#ref-sun2021estimating" role="doc-biblioref">Sun &amp; Abraham, 2021</a>)</span>, the doubly-robust DiD estimator from <span class="citation" data-cites="callaway2021difference">Callaway &amp; Sant’Anna (<a href="references.html#ref-callaway2021difference" role="doc-biblioref">2021</a>)</span>, and the Rambachan-Roth sensitivity analysis that quantifies how much parallel-trends violation it would take to overturn the conclusion <span class="citation" data-cites="rambachan2023more">(<a href="references.html#ref-rambachan2023more" role="doc-biblioref">Rambachan &amp; Roth, 2023</a>)</span>.</p>
<p>The dataset is no longer Proposition 99. Staggered DiD requires <strong>variation in treatment timing</strong>, which a single-treated-state panel cannot provide. We switch to the Callaway-Sant’Anna minimum-wage panel: 1,745 US counties × 2003–2007, with cohorts <span class="math inline">\(G \in \{0, 2004,
2006\}\)</span> indexing the year the county’s state first raised its minimum wage above the federal $5.15/h floor. The outcome is log teen employment.</p>
</section>
<section id="setup-and-data-1" class="level2" data-number="6.11">
<h2 data-number="6.11" class="anchored" data-anchor-id="setup-and-data-1"><span class="header-section-number">6.11</span> Setup and data</h2>
<pre class="{r}"><code>#| label: setup
#| message: false
#| warning: false
library(tidyverse)
library(did)
library(fixest)
library(twfeweights)
library(HonestDiD)
library(DRDID)
library(BMisc)
library(pte)
library(patchwork)
source("R/table_helpers.R")
source("R/honest_did.R")

set.seed(42)

knitr::opts_chunk$set(dev.args = list(bg = "transparent"))

theme_set(
  theme_minimal(base_size = 12) +
    theme(
      plot.background  = element_rect(fill = "transparent", color = NA),
      panel.background = element_rect(fill = "transparent", color = NA),
      panel.grid.major = element_line(color = "#94a3b8", linewidth = 0.25),
      panel.grid.minor = element_line(color = "#94a3b8", linewidth = 0.15),
      text             = element_text(color = "#94a3b8"),
      axis.text        = element_text(color = "#94a3b8"),
      strip.text       = element_text(color = "#94a3b8"),
      legend.text      = element_text(color = "#94a3b8")
    )
)</code></pre>
<p>The dataset ships as <code>data/cs_minwage.rds</code> in the chapter bundle. We follow the source-post convention of restricting to cohorts <span class="math inline">\(G \in
\{0, 2004, 2006, 2007\}\)</span>, dropping the Northeast region (<code>region == "1"</code>) for comparability, and then carving out a clean working panel without the late-2007 cohort and starting in 2003.</p>
<pre class="{r}"><code>#| label: data-load
mw_raw &lt;- readRDS("data/cs_minwage.rds") |&gt; as_tibble()

# Step 1: drop Northeast and keep cohorts of interest.
mw &lt;- mw_raw |&gt;
  filter(G %in% c(0, 2004, 2006, 2007), region != "1")

# Step 2: working sample for the main analysis.
data2 &lt;- mw |&gt;
  filter(G != 2007, year &gt;= 2003)

dim(data2)</code></pre>
<p>The working panel has <code>r nrow(data2)</code> rows on <code>r length(unique(data2$id))</code> counties, balanced across the 2003–2007 window.</p>
<pre class="{r}"><code>#| label: tbl-cohort-counts
#| tbl-cap: "Cohort sizes in the working sample. G = 0 is the never-treated control pool; cohorts 2004 and 2006 are the staggered treated groups."
data2 |&gt;
  filter(year == 2003) |&gt;
  count(G, name = "counties") |&gt;
  rename(`Treatment cohort (G)` = G) |&gt;
  gt_pretty()</code></pre>
</section>
<section id="the-twfe-baseline-and-its-problem" class="level2" data-number="6.12">
<h2 data-number="6.12" class="anchored" data-anchor-id="the-twfe-baseline-and-its-problem"><span class="header-section-number">6.12</span> The TWFE baseline and its problem</h2>
<p>The natural first move is the TWFE regression. The variable <code>post</code> in the dataset is 1 in periods where the county’s state has already raised its minimum wage (i.e., <code>year &gt;= G &amp; G != 0</code>), and 0 otherwise.</p>
<pre class="{r}"><code>#| label: tbl-twfe
#| tbl-cap: "Two-way fixed-effects regression. The point estimate suggests minimum-wage increases cut log teen employment by roughly 3.8 percent — but see the diagnostic that follows."
twfe_res &lt;- fixest::feols(lemp ~ post | id + year,
                          data = data2, cluster = "id")
ms_pretty(list("TWFE (county + year FE)" = twfe_res),
          coef_map = c("post" = "Post (any cohort)"),
          notes    = "SEs clustered at the county level.")</code></pre>
<p>The TWFE coefficient is roughly <span class="math inline">\(-0.038\)</span>. Read literally, the policy reduced teen employment by 3.8 percent. Before believing it, two diagnostics are essential.</p>
<section id="sun-abraham-event-study" class="level3" data-number="6.12.1">
<h3 data-number="6.12.1" class="anchored" data-anchor-id="sun-abraham-event-study"><span class="header-section-number">6.12.1</span> Sun-Abraham event study</h3>
<p>The first is to allow the effect to <em>evolve</em> with time since treatment — an event-study specification. The naive interacted version, <span class="math inline">\(y_{it} = \alpha_i + \gamma_t + \sum_{k \ne -1} \beta_k \cdot
\mathbf{1}(t - G_i = k) + \varepsilon_{it}\)</span>, is itself biased in staggered designs. The <span class="citation" data-cites="sun2021estimating">Sun &amp; Abraham (<a href="references.html#ref-sun2021estimating" role="doc-biblioref">2021</a>)</span> fix is the interaction- weighted estimator implemented by <code>fixest::sunab()</code>.</p>
<pre class="{r}"><code>#| label: fig-sunab
#| fig-cap: "Sun-Abraham event study. Pre-treatment leads (negative event time) trend slightly below zero; post-treatment effects accumulate from -0.025 on impact to roughly -0.13 by event-time +3."
#| fig-width: 8
#| fig-height: 4.5
sa_res &lt;- fixest::feols(lemp ~ sunab(G, year) | id + year,
                        data = data2, cluster = "id")

sa_df &lt;- broom::tidy(sa_res, conf.int = TRUE) |&gt;
  filter(stringr::str_detect(term, "^year::")) |&gt;
  mutate(event_time = as.integer(stringr::str_remove(term, "^year::")))

ggplot(sa_df, aes(x = event_time, y = estimate)) +
  geom_hline(yintercept = 0, color = "#94a3b8", linetype = "dashed") +
  geom_vline(xintercept = -0.5, color = "#94a3b8", linetype = "dashed") +
  geom_point(color = "#22d3ee", size = 2.5) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high),
                color = "#22d3ee", width = 0.15) +
  labs(x = "Event time (years from first minimum-wage increase)",
       y = "Effect on log teen employment")</code></pre>
<p>A clean event study should show <strong>flat pre-treatment leads near zero</strong>, then post-treatment effects that look credible. The Sun-Abraham picture is mixed: a clearly negative on-impact effect that grows over time, but pre-trends that are not perfectly flat. This is the parallel-trends concern we will quantify with HonestDiD in section 7.</p>
</section>
<section id="twfe-weight-decomposition" class="level3" data-number="6.12.2">
<h3 data-number="6.12.2" class="anchored" data-anchor-id="twfe-weight-decomposition"><span class="header-section-number">6.12.2</span> TWFE weight decomposition</h3>
<p>The second diagnostic asks: among the underlying group-time comparisons that TWFE silently aggregates, <strong>what weights does it use?</strong> <span class="citation" data-cites="goodmanbacon2021difference">Goodman-Bacon (<a href="references.html#ref-goodmanbacon2021difference" role="doc-biblioref">2021</a>)</span> shows that TWFE weights <em>can</em> be negative, especially when an already-treated unit is being used as a control for a later-treated one. <code>twfeweights::twfe_weights()</code> and <code>twfeweights::attO_weights()</code> give us the weights TWFE actually applies and the weights an unbiased aggregator (the <span class="citation" data-cites="callaway2021difference">Callaway &amp; Sant’Anna (<a href="references.html#ref-callaway2021difference" role="doc-biblioref">2021</a>)</span> overall ATT) would apply for comparison.</p>
<pre class="{r}"><code>#| label: tbl-twfe-weight-summary
#| tbl-cap: "TWFE weight diagnostic. Negative or pre-treatment weights are a red flag — they mean TWFE is silently subtracting effects you would not want it to subtract."
attgt_for_weights &lt;- did::att_gt(
  yname = "lemp", idname = "id", gname = "G", tname = "year",
  data = data2, control_group = "nevertreated",
  base_period = "universal"
)

tw &lt;- twfeweights::twfe_weights(attgt_for_weights)
wO &lt;- twfeweights::attO_weights(attgt_for_weights)

tw_df &lt;- tibble(
  twfe_weight = tw$weights_df$weight,
  attO_weight = wO$weights_df$weight,
  post        = as.integer(as.character(tw$weights_df$post))
)

summary_tbl &lt;- tibble(
  `Weight source` = c("TWFE",
                      "TWFE (pre-treatment cells)",
                      "TWFE (post-treatment cells)",
                      "ATT-O (Callaway-Sant'Anna)"),
  `Min`        = c(min(tw_df$twfe_weight),
                   min(tw_df$twfe_weight[tw_df$post == 0]),
                   min(tw_df$twfe_weight[tw_df$post == 1]),
                   min(tw_df$attO_weight)),
  `Max`        = c(max(tw_df$twfe_weight),
                   max(tw_df$twfe_weight[tw_df$post == 0]),
                   max(tw_df$twfe_weight[tw_df$post == 1]),
                   max(tw_df$attO_weight)),
  `Sum`        = c(sum(tw_df$twfe_weight),
                   sum(tw_df$twfe_weight[tw_df$post == 0]),
                   sum(tw_df$twfe_weight[tw_df$post == 1]),
                   sum(tw_df$attO_weight))
)
gt_pretty(summary_tbl, decimals = 3)</code></pre>
<pre class="{r}"><code>#| label: fig-twfe-weights
#| fig-cap: "TWFE vs. Callaway-Sant'Anna overall-ATT weights for the same set of group-time cells. TWFE puts non-trivial mass on pre-treatment cells (negative weights, dashed line) and weights some post-treatment cells very differently from the unbiased target."
#| fig-width: 7.5
#| fig-height: 5
tw_plot &lt;- tw_df |&gt;
  mutate(period = ifelse(post == 1, "Post-treatment", "Pre-treatment"))

ggplot(tw_plot, aes(x = attO_weight, y = twfe_weight, color = period)) +
  geom_hline(yintercept = 0, color = "#94a3b8", linetype = "dashed") +
  geom_abline(slope = 1, intercept = 0,
              color = "#94a3b8", linetype = "dotted") +
  geom_point(size = 2.5, alpha = 0.7) +
  scale_color_manual(values = c("Pre-treatment"  = "#e2e8f0",
                                "Post-treatment" = "#22d3ee")) +
  labs(x = "Unbiased overall-ATT weight",
       y = "TWFE weight", color = NULL)</code></pre>
<p>The pre-treatment cells get weight from TWFE but zero weight from the unbiased ATT-O aggregator — this is the mechanism behind Goodman-Bacon’s “contamination” diagnosis. The dotted 45-degree line would mark perfect agreement.</p>
</section>
</section>
<section id="group-time-atts-the-callaway-santanna-approach" class="level2" data-number="6.13">
<h2 data-number="6.13" class="anchored" data-anchor-id="group-time-atts-the-callaway-santanna-approach"><span class="header-section-number">6.13</span> Group-time ATTs: the Callaway-Sant’Anna approach</h2>
<p>The fix is to estimate the <em>primitive</em> objects directly. For each cohort <span class="math inline">\(g\)</span> (a year a group of counties was first treated) and each calendar year <span class="math inline">\(t\)</span>, define</p>
<p><span class="math display">\[ATT(g, t) = \mathbb{E}\!\left[Y_{it}(g) - Y_{it}(\infty) \mid G_i = g\right],\]</span></p>
<p>the average effect on cohort <span class="math inline">\(g\)</span> in year <span class="math inline">\(t\)</span> relative to its own never-treated potential outcome. <code>did::att_gt()</code> estimates each of these from a clean 2×2 DiD using only cohort <span class="math inline">\(g\)</span> and an appropriate comparison group (here, the never-treated <span class="math inline">\(G = 0\)</span>), so no contamination from already-treated units sneaks in.</p>
<pre class="{r}"><code>#| label: tbl-attgt
#| tbl-cap: "Group-time average treatment effects $ATT(g, t)$ for the minimum-wage panel. Cohorts 2004 and 2006, each year 2003 through 2007. Pre-treatment cells should hover near zero if parallel trends holds; post-treatment cells are the effects we want."
attgt &lt;- did::att_gt(yname = "lemp", idname = "id", gname = "G",
                     tname = "year", data = data2,
                     control_group = "nevertreated",
                     base_period = "universal")

attgt_df &lt;- tibble(
  Cohort       = attgt$group,
  Year         = attgt$t,
  `ATT(g,t)`   = attgt$att,
  SE           = as.numeric(attgt$se)
) |&gt;
  mutate(`Treated?` = ifelse(Year &gt;= Cohort, "post", "pre")) |&gt;
  arrange(Cohort, Year)

gt_pretty(attgt_df, decimals = 4)</code></pre>
<section id="aggregation-overall-att-and-event-study" class="level3" data-number="6.13.1">
<h3 data-number="6.13.1" class="anchored" data-anchor-id="aggregation-overall-att-and-event-study"><span class="header-section-number">6.13.1</span> Aggregation: overall ATT and event study</h3>
<p>The 8 cells in <a href="09-staggered-did.html#tbl-attgt" class="quarto-xref">Table&nbsp;<span>9.4</span></a> are the primitives. They are not the headline. Aggregating them produces summaries that are valid in the presence of staggered adoption.</p>
<p>The <strong>overall ATT</strong> weights each post-treatment <span class="math inline">\(ATT(g, t)\)</span> by the size of cohort <span class="math inline">\(g\)</span>, then averages within cohort and over cohorts. It answers: <em>across treated counties and across the time they had been treated for, what is the average effect?</em></p>
<pre class="{r}"><code>#| label: tbl-cs-overall
#| tbl-cap: "Callaway-Sant'Anna overall ATT (sample-weighted aggregation across cohorts). This is the staggered-DiD analogue of chapter 4's single DiD coefficient."
attO &lt;- did::aggte(attgt, type = "group")

tibble(
  Estimator             = "Callaway-Sant'Anna overall ATT",
  `Estimate`            = attO$overall.att,
  `SE`                  = attO$overall.se,
  `CI lower`            = attO$overall.att - 1.96 * attO$overall.se,
  `CI upper`            = attO$overall.att + 1.96 * attO$overall.se
) |&gt; gt_pretty(decimals = 4)</code></pre>
<p>The overall ATT is roughly <span class="math inline">\(-0.057\)</span> — almost 50 percent larger in magnitude than the TWFE coefficient. The two estimands answer different questions, but the size of the gap is exactly the contamination problem in operation.</p>
<p>The <strong>event-study aggregation</strong> averages <span class="math inline">\(ATT(g, t)\)</span> within each event time <span class="math inline">\(e = t - g\)</span>, giving a curve of dynamic effects since treatment.</p>
<pre class="{r}"><code>#| label: tbl-cs-event
#| tbl-cap: "Callaway-Sant'Anna event-study aggregation. Event time -1 is the omitted reference period under the universal base."
attes &lt;- did::aggte(attgt, type = "dynamic")

tibble(
  `Event time` = attes$egt,
  `ATT(e)`     = attes$att.egt,
  SE           = attes$se.egt,
  `CI lower`   = attes$att.egt - 1.96 * attes$se.egt,
  `CI upper`   = attes$att.egt + 1.96 * attes$se.egt
) |&gt; gt_pretty(decimals = 4)</code></pre>
<pre class="{r}"><code>#| label: fig-cs-event
#| fig-cap: "Callaway-Sant'Anna event study. The on-impact effect is small; effects accumulate to roughly -0.13 log points by event-time +3 (three years post-treatment)."
#| fig-width: 8
#| fig-height: 4.5
cs_es_df &lt;- tibble(
  egt   = attes$egt,
  est   = attes$att.egt,
  se    = attes$se.egt,
  phase = ifelse(attes$egt &lt; 0, "Pre", "Post")
)

ggplot(cs_es_df, aes(x = egt, y = est, color = phase)) +
  geom_hline(yintercept = 0, color = "#94a3b8", linetype = "dashed") +
  geom_vline(xintercept = -0.5, color = "#94a3b8", linetype = "dashed") +
  geom_point(size = 2.8) +
  geom_errorbar(aes(ymin = est - 1.96 * se, ymax = est + 1.96 * se),
                width = 0.15) +
  scale_color_manual(values = c("Pre"  = "#e2e8f0",
                                "Post" = "#22d3ee")) +
  labs(x = "Event time (years from first minimum-wage increase)",
       y = "Effect on log teen employment", color = NULL)</code></pre>
</section>
</section>
<section id="conditional-parallel-trends" class="level2" data-number="6.14">
<h2 data-number="6.14" class="anchored" data-anchor-id="conditional-parallel-trends"><span class="header-section-number">6.14</span> Conditional parallel trends</h2>
<p>Plain DiD assumes parallel trends <em>unconditionally</em>. Conditional DiD allows trends to be parallel only after adjusting for observed covariates that shape the trajectory. In this dataset, log county population and log average county pay are obvious candidates: counties with bigger populations or higher-paying jobs may move on different underlying trajectories whether or not they raise the minimum wage.</p>
<p><code>did::att_gt()</code> accepts <code>xformla = ~lpop + lavg_pay</code> plus a choice of estimator: <strong>regression adjustment</strong> (impute the counterfactual mean from the never-treated), <strong>inverse probability weighting</strong> (reweight never-treated counties to look like treated ones), or <strong>doubly robust</strong> (the <span class="citation" data-cites="callaway2021difference">Callaway &amp; Sant’Anna (<a href="references.html#ref-callaway2021difference" role="doc-biblioref">2021</a>)</span> default, which is consistent if either the outcome model <em>or</em> the propensity score is correctly specified).</p>
<pre class="{r}"><code>#| label: tbl-conditional
#| tbl-cap: "Overall ATT under four identification assumptions: unconditional parallel trends, regression adjustment, inverse probability weighting, and doubly robust. The four point estimates land within roughly one SE of each other, which is reassuring."
#| message: false
#| warning: false

cs_reg &lt;- did::att_gt(yname="lemp", tname="year", idname="id", gname="G",
                      xformla = ~lpop + lavg_pay,
                      control_group = "nevertreated",
                      base_period = "universal",
                      est_method = "reg", data = data2)
attO_reg &lt;- did::aggte(cs_reg, type = "group")

cs_ipw &lt;- did::att_gt(yname="lemp", tname="year", idname="id", gname="G",
                      xformla = ~lpop + lavg_pay,
                      control_group = "nevertreated",
                      base_period = "universal",
                      est_method = "ipw", data = data2)
attO_ipw &lt;- did::aggte(cs_ipw, type = "group")

cs_dr  &lt;- did::att_gt(yname="lemp", tname="year", idname="id", gname="G",
                      xformla = ~lpop + lavg_pay,
                      control_group = "nevertreated",
                      base_period = "universal",
                      est_method = "dr", data = data2)
attO_dr  &lt;- did::aggte(cs_dr, type = "group")

tibble(
  Identification = c("Unconditional parallel trends",
                     "Conditional · regression adjustment",
                     "Conditional · IPW",
                     "Conditional · doubly robust"),
  Estimate = c(attO$overall.att, attO_reg$overall.att,
               attO_ipw$overall.att, attO_dr$overall.att),
  SE       = c(attO$overall.se,  attO_reg$overall.se,
               attO_ipw$overall.se,  attO_dr$overall.se)
) |&gt; gt_pretty(decimals = 4)</code></pre>
<p>The doubly-robust estimate is the most reliable in practice — it recovers a correct ATT if either the trend model or the selection model is right, where the other two require their respective model to be correctly specified.</p>
</section>
<section id="robustness-knobs" class="level2" data-number="6.15">
<h2 data-number="6.15" class="anchored" data-anchor-id="robustness-knobs"><span class="header-section-number">6.15</span> Robustness knobs</h2>
<p>Three knobs are worth turning to gauge how fragile the headline estimate is to design choices.</p>
<pre class="{r}"><code>#| label: tbl-robustness
#| tbl-cap: "Overall ATT under three robustness perturbations: shifting from a universal to a varying base period, switching the control group from never-treated to not-yet-treated, and allowing one year of anticipation."
#| message: false
#| warning: false

cs_var &lt;- did::att_gt(yname="lemp", tname="year", idname="id", gname="G",
                      xformla = ~lpop + lavg_pay,
                      control_group = "nevertreated",
                      base_period = "varying",
                      est_method = "dr", data = data2)
attO_var &lt;- did::aggte(cs_var, type = "group")

cs_nyt &lt;- did::att_gt(yname="lemp", tname="year", idname="id", gname="G",
                      xformla = ~lpop + lavg_pay,
                      control_group = "notyettreated",
                      base_period = "universal",
                      est_method = "dr", data = data2)
attO_nyt &lt;- did::aggte(cs_nyt, type = "group")

cs_ant &lt;- did::att_gt(yname="lemp", tname="year", idname="id", gname="G",
                      xformla = ~lpop + lavg_pay,
                      control_group = "nevertreated",
                      base_period = "universal",
                      est_method = "dr",
                      anticipation = 1, data = data2)
attO_ant &lt;- did::aggte(cs_ant, type = "group")

tibble(
  Specification = c("Doubly robust (baseline)",
                    "Varying base period",
                    "Not-yet-treated controls",
                    "Anticipation = 1 year"),
  Estimate = c(attO_dr$overall.att, attO_var$overall.att,
               attO_nyt$overall.att, attO_ant$overall.att),
  SE       = c(attO_dr$overall.se,  attO_var$overall.se,
               attO_nyt$overall.se,  attO_ant$overall.se)
) |&gt; gt_pretty(decimals = 4)</code></pre>
<p>None of the robustness checks moves the estimate by more than its own standard error. That is the strongest internal evidence we have that the design is identifying a stable effect.</p>
</section>
<section id="sensitivity-to-parallel-trends-violations" class="level2" data-number="6.16">
<h2 data-number="6.16" class="anchored" data-anchor-id="sensitivity-to-parallel-trends-violations"><span class="header-section-number">6.16</span> Sensitivity to parallel-trends violations</h2>
<p>The robustness table only varies <em>design</em> choices; it does not quantify <em>how much</em> parallel trends would have to be violated to overturn the conclusion. <span class="citation" data-cites="rambachan2023more">Rambachan &amp; Roth (<a href="references.html#ref-rambachan2023more" role="doc-biblioref">2023</a>)</span> provide exactly that quantification. The <code>HonestDiD</code> package, paired with a small bridge function in <code>R/honest_did.R</code>, lets us bound the post-treatment effect under the assumption that any unobserved pre-trend violation is at most <span class="math inline">\(\bar M\)</span> times the largest <em>observed</em> pre-trend violation.</p>
<pre class="{r}"><code>#| label: tbl-honest
#| tbl-cap: "Robust confidence intervals for the on-impact effect $ATT(e = 0)$ under the relative-magnitude restriction. As $\\bar M$ grows, the CI widens; we report the breakdown point — the $\\bar M$ at which the CI first contains zero."
#| message: false
#| warning: false

attgt_hd &lt;- did::att_gt(yname="lemp", idname="id", gname="G",
                        tname="year", data=data2,
                        control_group="nevertreated",
                        base_period="universal")
cs_es_hd &lt;- did::aggte(attgt_hd, type="dynamic")

hd_rm &lt;- honest_did(es      = cs_es_hd,
                    e       = 0,
                    type    = "relative_magnitude",
                    method  = "C-LF",
                    Mbarvec = seq(0, 2, by = 0.5))

hd_rm |&gt;
  transmute(`$\\bar M$` = Mbar,
            `CI lower`  = lb,
            `CI upper`  = ub,
            `Contains 0?` = ifelse(lb &lt;= 0 &amp; 0 &lt;= ub, "yes", "no")) |&gt;
  gt_pretty(decimals = 4)</code></pre>
<pre class="{r}"><code>#| label: fig-honest
#| fig-cap: "HonestDiD sensitivity: as $\\bar M$ grows, the robust 95 percent CI on the on-impact effect widens until it crosses zero. The breakdown $\\bar M$ is roughly 1; effects of the magnitude observed in the data survive any pre-trend violation up to that size."
#| fig-width: 7.5
#| fig-height: 4.5
ggplot(hd_rm, aes(x = Mbar)) +
  geom_hline(yintercept = 0, color = "#94a3b8", linetype = "dashed") +
  geom_ribbon(aes(ymin = lb, ymax = ub),
              fill = "#22d3ee", alpha = 0.2) +
  geom_line(aes(y = lb), color = "#22d3ee", linewidth = 0.9) +
  geom_line(aes(y = ub), color = "#22d3ee", linewidth = 0.9) +
  labs(x = expression(bar(M)),
       y = "Robust 95% CI on ATT(e = 0)")</code></pre>
<p>The breakdown point is around <span class="math inline">\(\bar M \approx 1\)</span> — meaning the conclusion that minimum-wage increases reduce on-impact teen employment survives any unobserved pre-trend violation up to roughly the <em>largest observed pre-trend in the data</em>. That is a strong robustness result.</p>
</section>
<section id="heterogeneous-treatment-doses" class="level2" data-number="6.17">
<h2 data-number="6.17" class="anchored" data-anchor-id="heterogeneous-treatment-doses"><span class="header-section-number">6.17</span> Heterogeneous treatment doses</h2>
<p>State minimum wages were not raised by the same amount. Some states went to $5.50/h, others to $7.25/h. A natural refinement is to <strong>normalize</strong> each treated state’s effect by the size of the wage increase — an “ATT per dollar above the federal floor”.</p>
<p>We follow the source post in expanding the working sample to include the 2007 cohort (gives us more treated states and more variation in the dose) and applying <code>DRDID::drdid_panel()</code> cell by cell on the cohort-by-period contrasts, then dividing by the wage delta.</p>
<pre class="{r}"><code>#| label: dose-compute
#| message: false
#| warning: false

data3 &lt;- mw |&gt;
  filter(year &gt;= 2003)
treated_state_list &lt;- unique(subset(data3, G != 0)$state_name)

attlist &lt;- list()
for (state in treated_state_list) {
  g &lt;- unique(subset(data3, state_name == state)$G)
  for (period in 2004:2007) {
    if (period &lt; g) next  # only post-treatment cells

    treat_idx_post  &lt;- data3$state_name == state &amp; data3$year == period
    treat_idx_base  &lt;- data3$state_name == state &amp; data3$year == g - 1
    if (sum(treat_idx_post) == 0 || sum(treat_idx_base) == 0) next

    ctrl_idx_post  &lt;- data3$G == 0 &amp; data3$year == period
    ctrl_idx_base  &lt;- data3$G == 0 &amp; data3$year == g - 1

    Y1 &lt;- c(data3$lemp[treat_idx_post], data3$lemp[ctrl_idx_post])
    Y0 &lt;- c(data3$lemp[treat_idx_base], data3$lemp[ctrl_idx_base])
    D  &lt;- c(rep(1, sum(treat_idx_post)), rep(0, sum(ctrl_idx_post)))

    out &lt;- DRDID::drdid_panel(y1 = Y1, y0 = Y0, D = D, covariates = NULL)
    dose &lt;- unique(data3$state_mw[treat_idx_post]) - 5.15

    attlist[[paste(state, period, sep = "_")]] &lt;- tibble(
      state         = state,
      cohort        = g,
      event_time    = period - g,
      att           = out$ATT,
      se            = out$se,
      dose          = dose,
      att_per_dollar = out$ATT / dose
    )
  }
}

dose_df &lt;- bind_rows(attlist)
dose_summary &lt;- dose_df |&gt;
  group_by(event_time) |&gt;
  summarise(att_per_dollar_mean = mean(att_per_dollar),
            att_per_dollar_sd   = sd(att_per_dollar),
            n                   = n(),
            .groups = "drop")</code></pre>
<pre class="{r}"><code>#| label: tbl-dose
#| tbl-cap: "ATT per dollar of minimum-wage increase, averaged over treated states within each post-treatment event time. Effects grow with time since treatment."
dose_summary |&gt;
  rename(`Event time`       = event_time,
         `ATT per $ (mean)` = att_per_dollar_mean,
         `ATT per $ (SD)`   = att_per_dollar_sd,
         `# states`         = n) |&gt;
  gt_pretty(decimals = 4)</code></pre>
<pre class="{r}"><code>#| label: fig-dose
#| fig-cap: "ATT per dollar of minimum-wage increase by event time. Each grey point is a (state, event-time) cell; cyan points are the cross-state means at each event time."
#| fig-width: 7.5
#| fig-height: 4.5
ggplot(dose_df, aes(x = event_time, y = att_per_dollar)) +
  geom_hline(yintercept = 0, color = "#94a3b8", linetype = "dashed") +
  geom_jitter(width = 0.15, height = 0, alpha = 0.5, color = "#94a3b8") +
  stat_summary(fun = mean, geom = "point",
               color = "#22d3ee", size = 3.5) +
  labs(x = "Event time (years from first minimum-wage increase)",
       y = "ATT per $1 above federal floor")</code></pre>
</section>
<section id="lagged-outcomes-an-alternative-identifying-assumption" class="level2" data-number="6.18">
<h2 data-number="6.18" class="anchored" data-anchor-id="lagged-outcomes-an-alternative-identifying-assumption"><span class="header-section-number">6.18</span> Lagged outcomes: an alternative identifying assumption</h2>
<p>So far every estimator relied on <strong>parallel trends</strong> (conditional or unconditional). A different identifying assumption, popular in labor economics, is that <em>conditional on the lagged outcome</em>, treatment assignment is as good as random — the so-called <strong>lagged-outcomes</strong> or <strong>unconfoundedness on past Y</strong> strategy. The <code>pte</code> package implements this in the same group-time-aggregation framework as <code>did</code>.</p>
<pre class="{r}"><code>#| label: tbl-pte
#| tbl-cap: "Event-study estimates under the lagged-outcomes identifying assumption (pte::pte_default). The conditioning is on lagged log teen employment rather than on the parallel-trends assumption."
#| message: false
#| warning: false

data2_lo &lt;- data2 |&gt;
  mutate(G2 = G)

lo_res &lt;- pte::pte_default(yname = "lemp", tname = "year", idname = "id",
                           gname = "G2", data = as.data.frame(data2_lo),
                           d_outcome = FALSE, lagged_outcome_cov = TRUE)

tibble(
  `Event time` = lo_res$event_study$egt,
  `ATT(e)`     = lo_res$event_study$att.egt,
  SE           = lo_res$event_study$se.egt
) |&gt; gt_pretty(decimals = 4)</code></pre>
<p>The lagged-outcomes estimate of the overall negative effect is qualitatively similar to the parallel-trends-based estimates. Two very different identifying assumptions point to the same substantive conclusion — which is the strongest possible evidence the design generates.</p>
</section>
<section id="recap-1" class="level2" data-number="6.19">
<h2 data-number="6.19" class="anchored" data-anchor-id="recap-1"><span class="header-section-number">6.19</span> Recap</h2>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>The methods reconciled.</strong> TWFE on this dataset returned <span class="math inline">\(\hat\beta = -0.038\)</span>. The Callaway-Sant’Anna overall ATT is <span class="math inline">\(-0.057\)</span>. The doubly-robust conditional ATT is <span class="math inline">\(-0.065\)</span>. The event-study trajectory is <span class="math inline">\(\approx -0.024\)</span> on impact, dropping to <span class="math inline">\(\approx -0.13\)</span> by event-time <span class="math inline">\(+3\)</span>. HonestDiD sensitivity puts the breakdown <span class="math inline">\(\bar M\)</span> near 1.0. The lagged-outcomes estimator agrees in sign and magnitude. Five very different estimators tell the same story: <em>minimum-wage increases reduced teen employment in these counties, and the effect grew over time</em>.</p>
<p>The gap between the TWFE estimate and the modern aggregators is the contamination problem of <span class="citation" data-cites="goodmanbacon2021difference">Goodman-Bacon (<a href="references.html#ref-goodmanbacon2021difference" role="doc-biblioref">2021</a>)</span> made concrete. TWFE absorbs <span class="math inline">\(\sim 36\)</span> percent of its weight into pre-treatment cells and post-treatment cells with negative weights — both of which the unbiased Callaway-Sant’Anna aggregator avoids.</p>
</div>
</div>
</div>
</section>
<section id="common-pitfall-1" class="level2" data-number="6.20">
<h2 data-number="6.20" class="anchored" data-anchor-id="common-pitfall-1"><span class="header-section-number">6.20</span> Common pitfall</h2>
<p>Running TWFE on staggered data and reporting the coefficient as if it were a clean ATT. The bias is mechanical — already-treated units get used as controls for later-treated units, and treatment-effect heterogeneity over time then leaks into the coefficient with unintended signs. <strong>What to do instead.</strong> Estimate the <span class="math inline">\(\{ATT(g, t)\}\)</span> primitives directly with <code>did::att_gt()</code>, look at the cells, and only then aggregate with <code>aggte()</code> using a target that matches the question you actually want to answer. If you must run TWFE for a referee, run <code>twfeweights::twfe_weights()</code> and report the share of weight on pre-treatment cells.</p>
</section>
<section id="further-reading-1" class="level2" data-number="6.21">
<h2 data-number="6.21" class="anchored" data-anchor-id="further-reading-1"><span class="header-section-number">6.21</span> Further reading</h2>
<p>The Callaway-Sant’Anna framework, the Goodman-Bacon decomposition, and the Sun-Abraham interaction-weighted estimator are the three modern reference points for staggered DiD <span class="citation" data-cites="callaway2021difference goodmanbacon2021difference sun2021estimating">(<a href="references.html#ref-callaway2021difference" role="doc-biblioref">Callaway &amp; Sant’Anna, 2021</a>; <a href="references.html#ref-goodmanbacon2021difference" role="doc-biblioref">Goodman-Bacon, 2021</a>; <a href="references.html#ref-sun2021estimating" role="doc-biblioref">Sun &amp; Abraham, 2021</a>)</span>. The <code>did</code> package vignettes (<a href="https://bcallaway11.github.io/did/" class="uri">https://bcallaway11.github.io/did/</a>) are the canonical implementation reference. For sensitivity analysis, the <span class="citation" data-cites="rambachan2023more">Rambachan &amp; Roth (<a href="references.html#ref-rambachan2023more" role="doc-biblioref">2023</a>)</span> paper plus the <code>HonestDiD</code> package documentation cover both the smoothness and relative-magnitude bounds. <span class="citation" data-cites="dechaisemartin2020twoway">Chaisemartin &amp; D’Haultfœuille (<a href="references.html#ref-dechaisemartin2020twoway" role="doc-biblioref">2020</a>)</span> is the parallel critique of TWFE from the <code>DIDmultiplegt</code> perspective. <span class="citation" data-cites="callaway2022handbook">Callaway (<a href="references.html#ref-callaway2022handbook" role="doc-biblioref">2022</a>)</span> is a textbook-level synthesis.</p>
<p>For a longer R walkthrough that this chapter is adapted from, see the companion post at <a href="https://cmg777.github.io/post/r_did/" class="uri">https://cmg777.github.io/post/r_did/</a>.</p>
</section>
<section id="exercises" class="level2" data-number="6.22">
<h2 data-number="6.22" class="anchored" data-anchor-id="exercises"><span class="header-section-number">6.22</span> Exercises</h2>
<ol type="1">
<li>Re-estimate the overall ATT using <code>control_group = "notyettreated"</code> instead of <code>"nevertreated"</code>. Does the answer change? Explain why the standard error usually <em>shrinks</em> under this alternative.</li>
<li>Use <code>did::aggte(attgt, type = "calendar")</code> to aggregate by <em>calendar year</em> rather than event time. Which calendar year shows the largest treatment effect, and what substantive story does that suggest?</li>
<li>Run <code>HonestDiD</code> with <code>type = "smoothness"</code> instead of <code>"relative_magnitude"</code>, supplying <code>Mvec = seq(0, 0.05, by = 0.01)</code>. What does the breakdown <span class="math inline">\(M\)</span> say about the credibility of the parallel-trends assumption in this dataset?</li>
</ol>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-brodersen-causalimpact-talk" class="csl-entry" role="listitem">
Brodersen, K. H. (n.d.). <em>Inferring the effect of an event using <span>CausalImpact</span></em>. YouTube talk. Retrieved <a href="https://youtu.be/GTgZfCltMm8">https://youtu.be/GTgZfCltMm8</a>
</div>
<div id="ref-brodersen2015inferring" class="csl-entry" role="listitem">
Brodersen, K. H., Gallusser, F., Koehler, J., Remy, N., &amp; Scott, S. L. (2015). Inferring causal impact using <span>Bayesian</span> structural time-series models. <em>Annals of Applied Statistics</em>, <em>9</em>, 247–274. <a href="https://research.google.com/pubs/pub41854.html">https://research.google.com/pubs/pub41854.html</a>
</div>
<div id="ref-causalimpact-pkg" class="csl-entry" role="listitem">
Brodersen, K. H., &amp; Hauser, A. (n.d.). <em><span>CausalImpact</span> — an <span>R</span> package for causal inference using <span>Bayesian</span> structural time-series models</em>. <a href="https://google.github.io/CausalImpact/" class="uri">https://google.github.io/CausalImpact/</a>.
</div>
<div id="ref-callaway2022handbook" class="csl-entry" role="listitem">
Callaway, B. (2022). Difference-in-differences for policy evaluation. <em>Handbook of Labor, Human Resources, and Population Economics</em>. <a href="https://link.springer.com/referencework/10.1007/978-3-319-57365-6">https://link.springer.com/referencework/10.1007/978-3-319-57365-6</a>
</div>
<div id="ref-callaway2021difference" class="csl-entry" role="listitem">
Callaway, B., &amp; Sant’Anna, P. H. C. (2021). Difference-in-differences with multiple time periods. <em>Journal of Econometrics</em>, <em>225</em>(2), 200–230. <a href="https://doi.org/10.1016/j.jeconom.2020.12.001">https://doi.org/10.1016/j.jeconom.2020.12.001</a>
</div>
<div id="ref-dechaisemartin2020twoway" class="csl-entry" role="listitem">
Chaisemartin, C. de, &amp; D’Haultfœuille, X. (2020). Two-way fixed effects estimators with heterogeneous treatment effects. <em>American Economic Review</em>, <em>110</em>(9), 2964–2996. <a href="https://doi.org/10.1257/aer.20181169">https://doi.org/10.1257/aer.20181169</a>
</div>
<div id="ref-goodmanbacon2021difference" class="csl-entry" role="listitem">
Goodman-Bacon, A. (2021). Difference-in-differences with variation in treatment timing. <em>Journal of Econometrics</em>, <em>225</em>(2), 254–277. <a href="https://doi.org/10.1016/j.jeconom.2021.03.014">https://doi.org/10.1016/j.jeconom.2021.03.014</a>
</div>
<div id="ref-rambachan2023more" class="csl-entry" role="listitem">
Rambachan, A., &amp; Roth, J. (2023). A more credible approach to parallel trends. <em>Review of Economic Studies</em>, <em>90</em>(5), 2555–2591. <a href="https://doi.org/10.1093/restud/rdad018">https://doi.org/10.1093/restud/rdad018</a>
</div>
<div id="ref-sun2021estimating" class="csl-entry" role="listitem">
Sun, L., &amp; Abraham, S. (2021). Estimating dynamic treatment effects in event studies with heterogeneous treatment effects. <em>Journal of Econometrics</em>, <em>225</em>(2), 175–199. <a href="https://doi.org/10.1016/j.jeconom.2020.09.006">https://doi.org/10.1016/j.jeconom.2020.09.006</a>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-classical-synthetic-control.html" class="pagination-link" aria-label="Classical Synthetic Control">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Classical Synthetic Control</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-bayesian-spatial-sc.html" class="pagination-link" aria-label="Bayesian Spatial Synthetic Control">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Bayesian Spatial Synthetic Control</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Structural Bayesian Time Series"</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">## The BSTS / CausalImpact idea</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>Fit a **Bayesian structural time-series (BSTS)** model on the pre-period. Use *other states' cigarette sales* (and optionally covariates) as predictors. Project the fitted model forward as the counterfactual. The posterior over (observed − projected) gives a credible interval for the policy effect.</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>This is the only method in the book that delivers a *credible* interval — a direct probability statement about the parameter — rather than a frequentist confidence band or a Fisher exact $p$-value.</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="fu">## The model in two pieces</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>The BSTS counterfactual is</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>$$y_{1t} = \mu_t + \beta^\top x_t + \varepsilon_t, \quad t \le t^*$$</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>where $\mu_t$ is a local-level trend, $x_t$ are the control-series regressors (other states' <span class="in">`cigsale`</span>, plus optional covariates), and $t^*$ is the intervention date. California's outcome is *a slowly-evolving trend* **plus** *a linear combination of donor-state series* **plus** *a random error*.</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a><span class="in">```{mermaid}</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>%%| label: fig-bsts-counterfactual</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>%%| fig-cap: <span class="ot">"</span><span class="st">Decomposition of the BSTS counterfactual: a local-level trend, a regression on donor cigsale + covariates, and random error sum to ŷ₁ₜ, which is then subtracted from the observed series to give the policy effect.</span><span class="ot">"</span></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>flowchart TB</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>    subgraph <span class="ot">"</span><span class="st">BSTS counterfactual ŷ₁ₜ</span><span class="ot">"</span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>        TREND[<span class="ot">"</span><span class="st">μₜ — local-level trend&lt;br/&gt;(absorbs dynamics no control can explain)</span><span class="ot">"</span>]</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>        REG[<span class="ot">"</span><span class="st">β·xₜ — regression on donor cigsale + covariates&lt;br/&gt;(borrows from donor pool)</span><span class="ot">"</span>]</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>        ERR[<span class="ot">"</span><span class="st">εₜ — random error</span><span class="ot">"</span>]</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>    end</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>    TREND --&gt; Y[<span class="ot">"</span><span class="st">ŷ₁ₜ</span><span class="ot">"</span>]</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>    REG --&gt; Y</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>    ERR --&gt; Y</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>    Y --&gt; CMP[<span class="ot">"</span><span class="st">Observed y₁ₜ − ŷ₁ₜ&lt;br/&gt;= policy effect (with credible band)</span><span class="ot">"</span>]</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>    style TREND fill:<span class="co">#6a9bcc,stroke:#cbd5e0,color:#fff</span></span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>    style REG fill:<span class="co">#00d4c8,stroke:#cbd5e0,color:#141413</span></span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>    style ERR fill:<span class="co">#7a8395,stroke:#cbd5e0,color:#fff</span></span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>    style Y fill:<span class="co">#7A209F,stroke:#cbd5e0,color:#fff</span></span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>    style CMP fill:<span class="co">#d97757,stroke:#cbd5e0,color:#fff</span></span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>The trend $\mu_t$ absorbs the dynamics that no control series can explain; the regression term $\beta^\top x_t$ borrows information from the donor pool. After the model is fit on $t \le t^*$, it is projected forward and the posterior over $y_{1t} - \hat{y}_{1t}$ gives the credible interval for the policy effect.</span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a><span class="fu">## Setup and data</span></span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>**Packages.** <span class="in">`tidyverse`</span> covers wrangling and plotting. <span class="in">`CausalImpact`</span> is Google's wrapper around the <span class="in">`bsts`</span> (Bayesian Structural Time Series) package: it takes a wide matrix with the treated outcome in column 1 and donor series in the remaining columns, fits a Bayesian state-space model on the pre-period, projects forward as the counterfactual, and returns posterior means + 95% credible intervals on the pointwise and cumulative effects. <span class="in">`mice`</span> provides multiple imputation by chained equations — we use its random-forest mode to fill the missing covariate values before pivoting to wide form. The <span class="in">`R/table_helpers.R`</span> helper provides <span class="in">`gt_pretty()`</span> for the summary table.</span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb7-51"><a href="#cb7-51" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb7-52"><a href="#cb7-52" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb7-53"><a href="#cb7-53" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb7-54"><a href="#cb7-54" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb7-55"><a href="#cb7-55" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(CausalImpact)</span>
<span id="cb7-56"><a href="#cb7-56" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice)</span>
<span id="cb7-57"><a href="#cb7-57" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"R/table_helpers.R"</span>)</span>
<span id="cb7-58"><a href="#cb7-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-59"><a href="#cb7-59" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb7-60"><a href="#cb7-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-61"><a href="#cb7-61" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">dev.args =</span> <span class="fu">list</span>(<span class="at">bg =</span> <span class="st">"transparent"</span>))</span>
<span id="cb7-62"><a href="#cb7-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-63"><a href="#cb7-63" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(</span>
<span id="cb7-64"><a href="#cb7-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb7-65"><a href="#cb7-65" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb7-66"><a href="#cb7-66" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.background  =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb7-67"><a href="#cb7-67" aria-hidden="true" tabindex="-1"></a>      <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb7-68"><a href="#cb7-68" aria-hidden="true" tabindex="-1"></a>      <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">"#94a3b8"</span>, <span class="at">linewidth =</span> <span class="fl">0.25</span>),</span>
<span id="cb7-69"><a href="#cb7-69" aria-hidden="true" tabindex="-1"></a>      <span class="at">panel.grid.minor =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">"#94a3b8"</span>, <span class="at">linewidth =</span> <span class="fl">0.15</span>),</span>
<span id="cb7-70"><a href="#cb7-70" aria-hidden="true" tabindex="-1"></a>      <span class="at">text             =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#94a3b8"</span>),</span>
<span id="cb7-71"><a href="#cb7-71" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text        =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#94a3b8"</span>)</span>
<span id="cb7-72"><a href="#cb7-72" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-73"><a href="#cb7-73" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-74"><a href="#cb7-74" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb7-75"><a href="#cb7-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-76"><a href="#cb7-76" aria-hidden="true" tabindex="-1"></a>**Dataset.** Like Synthetic Control, this method uses the **full 39-state × 31-year panel**: every state other than California is potentially a regressor in the Bayesian counterfactual model, and the four covariates (<span class="in">`lnincome`</span>, <span class="in">`retprice`</span>, <span class="in">`age15to24`</span>, <span class="in">`beer`</span>) are candidate predictors too. We do not pre-filter or restrict the window. The dataset is loaded as-is and then reshaped from long to wide in the next section, which is the form <span class="in">`CausalImpact`</span> requires.</span>
<span id="cb7-77"><a href="#cb7-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-80"><a href="#cb7-80" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb7-81"><a href="#cb7-81" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: data-load</span></span>
<span id="cb7-82"><a href="#cb7-82" aria-hidden="true" tabindex="-1"></a>prop99 <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/proposition99.rds"</span>) <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>()</span>
<span id="cb7-83"><a href="#cb7-83" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb7-84"><a href="#cb7-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-85"><a href="#cb7-85" aria-hidden="true" tabindex="-1"></a>The loaded <span class="in">`prop99`</span> is the same 1,209-row × 7-column tibble used in chapter 5 (39 states × 31 years × the <span class="in">`cigsale`</span> outcome and four covariates). The next section deals with the missing covariate values and the long-to-wide reshape that CausalImpact requires.</span>
<span id="cb7-86"><a href="#cb7-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-87"><a href="#cb7-87" aria-hidden="true" tabindex="-1"></a><span class="fu">## Imputation and wide pivot</span></span>
<span id="cb7-88"><a href="#cb7-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-89"><a href="#cb7-89" aria-hidden="true" tabindex="-1"></a>CausalImpact wants a *wide* dataset with the treated outcome in column 1 and every control series in the remaining columns. The covariate columns have missing values (<span class="in">`lnincome`</span> is missing 16% of rows, <span class="in">`age15to24`</span> 32%, <span class="in">`beer`</span> 55%), so we fill them with single random-forest imputation from <span class="in">`mice`</span>.</span>
<span id="cb7-90"><a href="#cb7-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-93"><a href="#cb7-93" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb7-94"><a href="#cb7-94" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: impute-and-pivot</span></span>
<span id="cb7-95"><a href="#cb7-95" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb7-96"><a href="#cb7-96" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb7-97"><a href="#cb7-97" aria-hidden="true" tabindex="-1"></a><span class="co"># Fill in missing covariate values with one round of random-forest</span></span>
<span id="cb7-98"><a href="#cb7-98" aria-hidden="true" tabindex="-1"></a><span class="co"># multiple imputation (m = 1, method = "rf"). printFlag suppresses</span></span>
<span id="cb7-99"><a href="#cb7-99" aria-hidden="true" tabindex="-1"></a><span class="co"># console chatter.</span></span>
<span id="cb7-100"><a href="#cb7-100" aria-hidden="true" tabindex="-1"></a>prop99_imputed <span class="ot">&lt;-</span> prop99 <span class="sc">|&gt;</span></span>
<span id="cb7-101"><a href="#cb7-101" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mice</span>(<span class="at">m =</span> <span class="dv">1</span>, <span class="at">method =</span> <span class="st">"rf"</span>, <span class="at">printFlag =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-102"><a href="#cb7-102" aria-hidden="true" tabindex="-1"></a>  <span class="fu">complete</span>() <span class="sc">|&gt;</span></span>
<span id="cb7-103"><a href="#cb7-103" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>()</span>
<span id="cb7-104"><a href="#cb7-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-105"><a href="#cb7-105" aria-hidden="true" tabindex="-1"></a><span class="co"># Pivot the long panel to wide format: one column per (variable, state)</span></span>
<span id="cb7-106"><a href="#cb7-106" aria-hidden="true" tabindex="-1"></a><span class="co"># pair. CausalImpact requires the treated outcome in column 1, hence</span></span>
<span id="cb7-107"><a href="#cb7-107" aria-hidden="true" tabindex="-1"></a><span class="co"># relocate(cigsale_California) and drop the year index.</span></span>
<span id="cb7-108"><a href="#cb7-108" aria-hidden="true" tabindex="-1"></a>prop99_wide <span class="ot">&lt;-</span> prop99_imputed <span class="sc">|&gt;</span></span>
<span id="cb7-109"><a href="#cb7-109" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from  =</span> state,</span>
<span id="cb7-110"><a href="#cb7-110" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> <span class="fu">c</span>(cigsale, lnincome, beer, age15to24, retprice)) <span class="sc">|&gt;</span></span>
<span id="cb7-111"><a href="#cb7-111" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(cigsale_California) <span class="sc">|&gt;</span></span>
<span id="cb7-112"><a href="#cb7-112" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>year)</span>
<span id="cb7-113"><a href="#cb7-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-114"><a href="#cb7-114" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(prop99_wide)</span>
<span id="cb7-115"><a href="#cb7-115" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb7-116"><a href="#cb7-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-117"><a href="#cb7-117" aria-hidden="true" tabindex="-1"></a>The reported <span class="in">`dim()`</span> confirms the reshape: <span class="in">`prop99_wide`</span> is **31 rows × 195 columns** — one row per year 1970–2000, and 39 states × 5 variables in the columns (<span class="in">`cigsale_*`</span>, <span class="in">`lnincome_*`</span>, <span class="in">`beer_*`</span>, <span class="in">`age15to24_*`</span>, <span class="in">`retprice_*`</span> for each of the 39 states), with <span class="in">`year`</span> dropped and <span class="in">`cigsale_California`</span> relocated to column 1 because that's what <span class="in">`CausalImpact()`</span> expects as the treated outcome.</span>
<span id="cb7-118"><a href="#cb7-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-119"><a href="#cb7-119" aria-hidden="true" tabindex="-1"></a><span class="fu">## Fit the Bayesian structural TS model</span></span>
<span id="cb7-120"><a href="#cb7-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-121"><a href="#cb7-121" aria-hidden="true" tabindex="-1"></a>**The fit.** The chunk below calls <span class="in">`CausalImpact(prop99_wide, pre.period, post.period)`</span> with the pre and post windows expressed as *integer row indices* (not years): row 1 is 1970, row 19 is 1988 (the last pre-period year), row 20 is 1989, row 31 is 2000. The seed is reset just before the call because `bsts` uses an MCMC sampler under the hood; a fixed seed makes the posterior draws reproducible from one render to the next. The returned `impact_full$summary` is a two-row data frame — one row for the *average* effect over 1989–2000 and one row for the *cumulative* effect — with posterior means and 95% credible bounds for each. The helper code below the <span class="in">`CausalImpact()`</span> call just formats those columns into the table.</span>
<span id="cb7-122"><a href="#cb7-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-125"><a href="#cb7-125" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb7-126"><a href="#cb7-126" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-causalimpact</span></span>
<span id="cb7-127"><a href="#cb7-127" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "CausalImpact posterior summary; brackets are 95% credible intervals."</span></span>
<span id="cb7-128"><a href="#cb7-128" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb7-129"><a href="#cb7-129" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb7-130"><a href="#cb7-130" aria-hidden="true" tabindex="-1"></a><span class="co"># CausalImpact takes integer row indices, not years.</span></span>
<span id="cb7-131"><a href="#cb7-131" aria-hidden="true" tabindex="-1"></a><span class="co"># Row 1 = 1970, row 19 = 1988 (last pre-period year).</span></span>
<span id="cb7-132"><a href="#cb7-132" aria-hidden="true" tabindex="-1"></a><span class="co"># Row 20 = 1989, row 31 = 2000 (last observed year).</span></span>
<span id="cb7-133"><a href="#cb7-133" aria-hidden="true" tabindex="-1"></a>pre_idx  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">19</span>)</span>
<span id="cb7-134"><a href="#cb7-134" aria-hidden="true" tabindex="-1"></a>post_idx <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">31</span>)</span>
<span id="cb7-135"><a href="#cb7-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-136"><a href="#cb7-136" aria-hidden="true" tabindex="-1"></a><span class="co"># Reset the seed so the BSTS MCMC draws are reproducible.</span></span>
<span id="cb7-137"><a href="#cb7-137" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb7-138"><a href="#cb7-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-139"><a href="#cb7-139" aria-hidden="true" tabindex="-1"></a>impact_full <span class="ot">&lt;-</span> <span class="fu">CausalImpact</span>(prop99_wide,</span>
<span id="cb7-140"><a href="#cb7-140" aria-hidden="true" tabindex="-1"></a>                            <span class="at">pre.period  =</span> pre_idx,</span>
<span id="cb7-141"><a href="#cb7-141" aria-hidden="true" tabindex="-1"></a>                            <span class="at">post.period =</span> post_idx)</span>
<span id="cb7-142"><a href="#cb7-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-143"><a href="#cb7-143" aria-hidden="true" tabindex="-1"></a>ci_summary <span class="ot">&lt;-</span> impact_full<span class="sc">$</span>summary <span class="sc">|&gt;</span></span>
<span id="cb7-144"><a href="#cb7-144" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">rownames_to_column</span>(<span class="st">"Horizon"</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-145"><a href="#cb7-145" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">transmute</span>(</span>
<span id="cb7-146"><a href="#cb7-146" aria-hidden="true" tabindex="-1"></a>    Horizon,</span>
<span id="cb7-147"><a href="#cb7-147" aria-hidden="true" tabindex="-1"></a>    <span class="at">Actual            =</span> <span class="fu">sprintf</span>(<span class="st">"%.1f"</span>, Actual),</span>
<span id="cb7-148"><a href="#cb7-148" aria-hidden="true" tabindex="-1"></a>    <span class="at">Prediction        =</span> <span class="fu">sprintf</span>(<span class="st">"%.1f [%.1f, %.1f]"</span>,</span>
<span id="cb7-149"><a href="#cb7-149" aria-hidden="true" tabindex="-1"></a>                                Pred, Pred.lower, Pred.upper),</span>
<span id="cb7-150"><a href="#cb7-150" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Absolute effect</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sprintf</span>(<span class="st">"%.1f [%.1f, %.1f]"</span>,</span>
<span id="cb7-151"><a href="#cb7-151" aria-hidden="true" tabindex="-1"></a>                                AbsEffect, AbsEffect.lower, AbsEffect.upper),</span>
<span id="cb7-152"><a href="#cb7-152" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Relative effect</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sprintf</span>(<span class="st">"%.1f%% [%.1f%%, %.1f%%]"</span>,</span>
<span id="cb7-153"><a href="#cb7-153" aria-hidden="true" tabindex="-1"></a>                                RelEffect <span class="sc">*</span> <span class="dv">100</span>, RelEffect.lower <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb7-154"><a href="#cb7-154" aria-hidden="true" tabindex="-1"></a>                                RelEffect.upper <span class="sc">*</span> <span class="dv">100</span>),</span>
<span id="cb7-155"><a href="#cb7-155" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Posterior p</span><span class="st">`</span>     <span class="ot">=</span> <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, p)</span>
<span id="cb7-156"><a href="#cb7-156" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-157"><a href="#cb7-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-158"><a href="#cb7-158" aria-hidden="true" tabindex="-1"></a><span class="fu">gt_pretty</span>(ci_summary)</span>
<span id="cb7-159"><a href="#cb7-159" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb7-160"><a href="#cb7-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-161"><a href="#cb7-161" aria-hidden="true" tabindex="-1"></a>**Reading the output.**</span>
<span id="cb7-162"><a href="#cb7-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-163"><a href="#cb7-163" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Average ATT:** approximately $-13$ packs/capita (posterior SD ≈ 11), 95% credible interval roughly $<span class="co">[</span><span class="ot">-32, +5.7</span><span class="co">]</span>$.</span>
<span id="cb7-164"><a href="#cb7-164" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Cumulative effect:** about $-154$ packs over 12 years, or roughly 16% of what would have been expected absent the policy.</span>
<span id="cb7-165"><a href="#cb7-165" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Posterior probability of any causal effect:** ≈ 92%.</span>
<span id="cb7-166"><a href="#cb7-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-167"><a href="#cb7-167" aria-hidden="true" tabindex="-1"></a>If we drop the covariates and use only other states' cigarette sales as controls, the point estimate strengthens to around $-21$ packs and the posterior probability rises to ≈ 97%. The covariates absorb some of the variation the simpler model was attributing to Proposition 99 — which can be read as either "added robustness" or "watered-down signal" depending on how much you trust the imputed beer-and-income covariates.</span>
<span id="cb7-168"><a href="#cb7-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-169"><a href="#cb7-169" aria-hidden="true" tabindex="-1"></a><span class="fu">## The two-panel diagnostic</span></span>
<span id="cb7-170"><a href="#cb7-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-171"><a href="#cb7-171" aria-hidden="true" tabindex="-1"></a>**What to look for.** Calling `plot()` on a `CausalImpact` object returns its default two-panel figure: the **top panel** shows observed California (solid line) against the Bayesian counterfactual (dashed) with its 95% credible band; the **bottom panel** shows the *cumulative* gap — the running sum of <span class="in">`observed − counterfactual`</span> from the intervention date onwards, with its own credible band. Read the top panel for whether and when the policy effect opens up, and the bottom panel for whether the cumulative effect's credible band excludes zero by the end of the series.</span>
<span id="cb7-172"><a href="#cb7-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-175"><a href="#cb7-175" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb7-176"><a href="#cb7-176" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-causalimpact</span></span>
<span id="cb7-177"><a href="#cb7-177" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "CausalImpact two-panel: pointwise observed vs Bayesian counterfactual, and cumulative effect over time."</span></span>
<span id="cb7-178"><a href="#cb7-178" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb7-179"><a href="#cb7-179" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 7</span></span>
<span id="cb7-180"><a href="#cb7-180" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(impact_full)</span>
<span id="cb7-181"><a href="#cb7-181" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb7-182"><a href="#cb7-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-183"><a href="#cb7-183" aria-hidden="true" tabindex="-1"></a>The top panel shows the pointwise picture: observed California opens a steady gap below the Bayesian counterfactual starting in 1989, with a 95% credible band that widens as we forecast further from the training window. The bottom panel cumulates that gap over time. By 2000 the cumulative effect is roughly $-150$ packs/capita with a credible interval that includes zero only at the very upper edge.</span>
<span id="cb7-184"><a href="#cb7-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-185"><a href="#cb7-185" aria-hidden="true" tabindex="-1"></a><span class="fu">## Common pitfall</span></span>
<span id="cb7-186"><a href="#cb7-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-187"><a href="#cb7-187" aria-hidden="true" tabindex="-1"></a>Imputing missing covariates without thinking about the imputation model. The random-forest fill we use here is a single-imputation shortcut for tutorial speed. With multiple imputation ($m &gt; 1$) or a different model, the estimate can move by 1–3 packs. Two concrete failure modes are worth spelling out, because they affect the credibility of the headline number rather than just its width.</span>
<span id="cb7-188"><a href="#cb7-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-189"><a href="#cb7-189" aria-hidden="true" tabindex="-1"></a>**Example 1 — Imputing donor covariates with a model that "sees" California.** Our <span class="in">`mice(prop99, ...)`</span> call passes the entire panel — California rows included — into the imputation model. For this dataset, with only four covariates and most missingness clustered in <span class="in">`beer`</span> (≈55%) and <span class="in">`age15to24`</span> (≈32%) on donor states, the consequence is usually mild. But if you were to feed the *full panel with the post-period California outcome attached* into an imputer that also uses `cigsale` as a predictor, the imputer could learn from California's post-1989 trajectory and propagate that information back into donor states' missing covariate cells. CausalImpact would then build a counterfactual that mechanically tracks California's post-period — biasing the estimated effect *toward zero* by construction. The safe pattern is to impute donor covariates *before* the treated outcome is in scope, or to drop the treated unit from the imputer entirely and impute donors only.</span>
<span id="cb7-190"><a href="#cb7-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-191"><a href="#cb7-191" aria-hidden="true" tabindex="-1"></a>**Example 2 — Single (`m = 1`) vs multiple (`m = 5`) imputation.** Single imputation treats the imputed values as if they were observed, then propagates that pretend-observed dataset through <span class="in">`CausalImpact`</span>. The posterior credible band you get back is the model's uncertainty *given* the imputed cells — it knows nothing about the uncertainty *introduced by the imputation itself*. With proper multiple imputation (<span class="in">`mice(..., m = 5)`</span> and Rubin's-rules pooling across the five resulting fits), the credible band widens by roughly 1–3 packs on this dataset because the across-imputation variance is added to the within-imputation variance. The point estimate barely moves; the interval does. For a tutorial we keep <span class="in">`m = 1`</span> for speed and clarity, but a published number should use <span class="in">`m ≥ 5`</span> and report a pooled estimate.</span>
<span id="cb7-192"><a href="#cb7-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-193"><a href="#cb7-193" aria-hidden="true" tabindex="-1"></a><span class="fu">## Recap</span></span>
<span id="cb7-194"><a href="#cb7-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-195"><a href="#cb7-195" aria-hidden="true" tabindex="-1"></a>CausalImpact lands at $-13$ to $-21$ packs depending on whether covariates are included, with a 92–97% posterior probability of a non-zero effect. It is the only method in the book that delivers a *credible* interval (a direct probability statement about the parameter), not a frequentist confidence band.</span>
<span id="cb7-196"><a href="#cb7-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-197"><a href="#cb7-197" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Question <span class="pp">|</span> Answer <span class="pp">|</span></span>
<span id="cb7-198"><a href="#cb7-198" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb7-199"><a href="#cb7-199" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> What does CausalImpact estimate? <span class="pp">|</span> The ATT on California, 1989–2000 <span class="pp">|</span></span>
<span id="cb7-200"><a href="#cb7-200" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> What is the point estimate? <span class="pp">|</span> Average ≈ $-13$ packs/capita; cumulative ≈ $-154$ packs over 12 years <span class="pp">|</span></span>
<span id="cb7-201"><a href="#cb7-201" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> What is the uncertainty quantification? <span class="pp">|</span> 95% Bayesian credible interval ≈ $<span class="co">[</span><span class="ot">-32, +5.7</span><span class="co">]</span>$ packs; posterior probability of any effect ≈ 92% <span class="pp">|</span></span>
<span id="cb7-202"><a href="#cb7-202" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> How is the counterfactual built? <span class="pp">|</span> Local-level trend + Bayesian regression on donor-state cigarette sales (+ imputed covariates) <span class="pp">|</span></span>
<span id="cb7-203"><a href="#cb7-203" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> What is the design-time pitfall? <span class="pp">|</span> Single-imputation shortcuts on covariates with high missingness; never impute donors using the treated unit <span class="pp">|</span></span>
<span id="cb7-204"><a href="#cb7-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-205"><a href="#cb7-205" aria-hidden="true" tabindex="-1"></a><span class="fu">## Further reading</span></span>
<span id="cb7-206"><a href="#cb7-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-207"><a href="#cb7-207" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>@brodersen2015inferring — the original <span class="in">`CausalImpact`</span> paper.</span>
<span id="cb7-208"><a href="#cb7-208" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>@brodersen-causalimpact-talk — a 50-minute walk-through of the CausalImpact intuition by the package's lead author.</span>
<span id="cb7-209"><a href="#cb7-209" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>@causalimpact-pkg — package documentation and worked examples.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/quarcs-lab/ccm/edit/main/06-structural-bayesian-ts.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/quarcs-lab/ccm/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script>
document.addEventListener('DOMContentLoaded', function() {
  var tocNav = document.getElementById('TOC');
  if (tocNav) {
    var coverDiv = document.createElement('div');
    coverDiv.id = 'toc-cover-image';
    var img = document.createElement('img');
    img.src = 'images/cover1.jpg';
    img.alt = 'Comparative Causal Metrics';
    coverDiv.appendChild(img);
    tocNav.parentNode.insertBefore(coverDiv, tocNav);
  }
});
document.addEventListener('DOMContentLoaded', function() {
  var parts = window.location.pathname.replace(/\/$/, '').split('/');
  var basename = parts[parts.length - 1].replace(/\.html$/, '');
  var m = basename.match(/^(\d{2})-/);
  if (!m) return;
  var btn = document.getElementById('quarto-code-tools-menu');
  if (!btn) return;
  var menu = btn.nextElementSibling;
  if (!menu || !menu.classList.contains('dropdown-menu')) return;
  var divider = document.createElement('li');
  divider.innerHTML = '<hr class="dropdown-divider">';
  menu.appendChild(divider);
  var item = document.createElement('li');
  item.innerHTML = '<a class="dropdown-item" href="downloads/chapter-' +
    m[1] + '.zip" download><i class="bi bi-download"></i> Download chapter (.zip)</a>';
  menu.appendChild(item);
});
</script>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>